import json, os

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

# ── SEC 11-12: MODEL TRAINING ──────────────────────────────────────────────────
NB["cells"].append(md(
    "### Section 11 & 12: Model Training — Logistic Regression vs. XGBoost\n\n"
    "Both models use identical training pairs, validation pairs, and features.\n"
    "No large hyperparameter search is performed.\n"
))
NB["cells"].append(code(
    "from sklearn.linear_model import LogisticRegression\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "\n"
    "print('Training Model A: Logistic Regression...')\n"
    "t_lr = time.time()\n"
    "scaler = StandardScaler()\n"
    "X_train_sc = scaler.fit_transform(X_train)\n"
    "X_val_sc   = scaler.transform(X_val)\n"
    "lr_model = LogisticRegression(C=1.0, max_iter=500, random_state=SEED, solver='lbfgs')\n"
    "lr_model.fit(X_train_sc, y_train)\n"
    "lr_time = time.time() - t_lr\n"
    "lr_val_probs = lr_model.predict_proba(X_val_sc)[:,1]\n"
    "print(f'  Logistic Regression trained in {lr_time:.2f}s')\n"
    "\n"
    "print('Training Model B: XGBoost...')\n"
    "t_xgb = time.time()\n"
    "xgb_model = xgb.XGBClassifier(\n"
    "    n_estimators=300, max_depth=6, learning_rate=0.08,\n"
    "    subsample=0.8, colsample_bytree=0.8,\n"
    "    tree_method='hist', random_state=SEED, n_jobs=8\n"
    ")\n"
    "xgb_model.fit(X_train, y_train)\n"
    "xgb_time = time.time() - t_xgb\n"
    "xgb_val_probs = xgb_model.predict_proba(X_val)[:,1]\n"
    "print(f'  XGBoost trained in {xgb_time:.2f}s')\n"
    "\n"
    "importances = xgb_model.feature_importances_\n"
    "top_idx = np.argsort(importances)[::-1][:10]\n"
    "print('\\nTop 10 XGBoost Feature Importances:')\n"
    "for r, idx in enumerate(top_idx, 1):\n"
    "    print(f'  {r:>2}. {FEATURE_NAMES[idx]:<28}: {importances[idx]*100:5.2f}%')\n"
))

# ── SEC 13-14: F0.5 UNIT TESTS + THRESHOLD SEARCH ─────────────────────────────
NB["cells"].append(md(
    "### Section 13 & 14: Macro F0.5 — Unit Tests + Threshold Search\n\n"
    "**Unit tests** verify the F0.5 implementation against 6 manually constructed cases before\n"
    "running the threshold grid. The threshold grid uses validation data only.\n\n"
    "Cases tested:\n"
    "- A: true empty + predicted empty → F0.5 = 1.0\n"
    "- B: true empty + false prediction → F0.5 = 0.0\n"
    "- C: one true match + correct prediction → F0.5 = 1.0\n"
    "- D: one true match + wrong prediction → F0.5 = 0.0\n"
    "- E: multiple true matches + partial prediction → 0 < F0.5 < 1\n"
    "- F: multiple true matches + extra false positive → F0.5 penalised\n"
))
NB["cells"].append(code(
    "from collections import defaultdict\n"
    "from sklearn.metrics import roc_auc_score, average_precision_score, f1_score\n"
    "\n"
    "def compute_entity_f05(true_matches, pred_matches):\n"
    "    \"\"\"Compute per-entity F0.5. true_matches and pred_matches are sets.\"\"\"\n"
    "    if not true_matches:\n"
    "        return 1.0 if not pred_matches else 0.0\n"
    "    if not pred_matches:\n"
    "        return 0.0\n"
    "    tp = len(true_matches & pred_matches)\n"
    "    if tp == 0:\n"
    "        return 0.0\n"
    "    prec = tp / len(pred_matches)\n"
    "    rec  = tp / len(true_matches)\n"
    "    denom = 0.25 * prec + rec\n"
    "    return (1.25 * prec * rec) / denom if denom > 0 else 0.0\n"
    "\n"
    "# ── UNIT TESTS ────────────────────────────────────────────────────────────\n"
    "print('=' * 60)\n"
    "print('F0.5 UNIT TESTS')\n"
    "print('=' * 60)\n"
    "\n"
    "unit_tests = [\n"
    "    ('A: true empty + pred empty',        set(),       set(),       1.0),\n"
    "    ('B: true empty + false pred',         set(),       {'x1'},      0.0),\n"
    "    ('C: one true match + correct pred',   {'m1'},      {'m1'},      1.0),\n"
    "    ('D: one true match + wrong pred',     {'m1'},      {'m2'},      0.0),\n"
    "    ('E: multi true + partial pred',       {'m1','m2'}, {'m1'},      None),\n"
    "    ('F: multi true + extra FP',           {'m1','m2'}, {'m1','m2','fp1'}, None),\n"
    "]\n"
    "\n"
    "all_passed = True\n"
    "for name, true_s, pred_s, expected in unit_tests:\n"
    "    got = compute_entity_f05(true_s, pred_s)\n"
    "    if expected is not None:\n"
    "        ok = abs(got - expected) < 1e-9\n"
    "        status = '[PASS]' if ok else '[FAIL]'\n"
    "        if not ok: all_passed = False\n"
    "        print(f'  {status} {name}: expected={expected:.4f} got={got:.4f}')\n"
    "    else:\n"
    "        # Sanity: must be in (0,1)\n"
    "        ok = 0.0 < got < 1.0\n"
    "        status = '[PASS]' if ok else '[FAIL]'\n"
    "        if not ok: all_passed = False\n"
    "        print(f'  {status} {name}: got={got:.4f} (expected 0 < F0.5 < 1)')\n"
    "\n"
    "# Case E explicit check: partial recall should give specific value\n"
    "e_got = compute_entity_f05({'m1','m2'}, {'m1'})\n"
    "# tp=1, prec=1.0, rec=0.5 => F0.5 = 1.25*1.0*0.5/(0.25*1.0+0.5) = 0.625/0.75 = 0.8333\n"
    "e_exp = 1.25*1.0*0.5/(0.25*1.0+0.5)\n"
    "ok_e = abs(e_got - e_exp) < 1e-6\n"
    "print(f'  {\"[PASS]\" if ok_e else \"[FAIL]\"} Case E exact value: expected={e_exp:.4f} got={e_got:.4f}')\n"
    "if not ok_e: all_passed = False\n"
    "\n"
    "# Case F: tp=2, prec=2/3, rec=1.0 => F0.5 = 1.25*(2/3)*1.0/(0.25*(2/3)+1.0)\n"
    "f_got = compute_entity_f05({'m1','m2'}, {'m1','m2','fp1'})\n"
    "f_exp = 1.25*(2/3)*1.0/(0.25*(2/3)+1.0)\n"
    "ok_f = abs(f_got - f_exp) < 1e-6\n"
    "print(f'  {\"[PASS]\" if ok_f else \"[FAIL]\"} Case F exact value: expected={f_exp:.4f} got={f_got:.4f}')\n"
    "if not ok_f: all_passed = False\n"
    "\n"
    "if not all_passed:\n"
    "    raise AssertionError('F0.5 unit tests FAILED. Fix compute_entity_f05 before proceeding.')\n"
    "print('All F0.5 unit tests passed.\\n')\n"
    "\n"
    "# ── BUILD VALIDATION GT MAP ────────────────────────────────────────────────\n"
    "# Every validation S1 must be evaluated (including singletons)\n"
    "val_gt_rows = con.execute(\"SELECT entity_id, matched_entity_ids FROM s1_split WHERE split='val'\").fetchall()\n"
    "val_gt = {}\n"
    "for sid, mstr in val_gt_rows:\n"
    "    if mstr and str(mstr).strip():\n"
    "        val_gt[sid] = {m.strip() for m in str(mstr).split(',') if m.strip()}\n"
    "    else:\n"
    "        val_gt[sid] = set()  # singleton: true empty set\n"
    "print(f'Validation S1 entities in GT map: {len(val_gt):,}')\n"
    "print(f'  Singletons (true empty): {sum(1 for v in val_gt.values() if not v):,}')\n"
    "print(f'  Non-singletons:          {sum(1 for v in val_gt.values() if v):,}')\n"
    "\n"
    "# Verify all val S1s have candidates (or will get empty prediction)\n"
    "val_s1_with_cands = set(r[0] for r in con.execute(\"SELECT DISTINCT s1_id FROM labeled_topk WHERE split='val'\").fetchall())\n"
    "val_s1_no_cands = set(val_gt.keys()) - val_s1_with_cands\n"
    "print(f'  Val S1s with no candidates (will predict empty): {len(val_s1_no_cands):,}')\n"
    "\n"
    "# ── THRESHOLD GRID SEARCH ─────────────────────────────────────────────────\n"
    "def evaluate_threshold_grid(val_probs, model_name):\n"
    "    scores_by_s1 = defaultdict(list)\n"
    "    for s1_id, tgt_id, prob in zip(df_val_pairs['s1_id'].values,\n"
    "                                    df_val_pairs['target_id'].values, val_probs):\n"
    "        scores_by_s1[s1_id].append((tgt_id, float(prob)))\n"
    "\n"
    "    thresholds = [round(t,2) for t in np.arange(0.30, 0.96, 0.05)]\n"
    "    results, best_row, best_f05 = [], None, -1.0\n"
    "\n"
    "    for tau in thresholds:\n"
    "        f05_list = []\n"
    "        total_tp = total_fp = total_fn = total_preds = 0\n"
    "        # Evaluate EVERY validation S1 (including singletons and those with no candidates)\n"
    "        for sid, true_set in val_gt.items():\n"
    "            cands    = scores_by_s1.get(sid, [])\n"
    "            pred_set = {tid for tid, prob in cands if prob >= tau}\n"
    "            f05_list.append(compute_entity_f05(true_set, pred_set))\n"
    "            total_tp    += len(true_set & pred_set)\n"
    "            total_fp    += len(pred_set - true_set)\n"
    "            total_fn    += len(true_set - pred_set)\n"
    "            total_preds += len(pred_set)\n"
    "\n"
    "        macro_f05 = float(np.mean(f05_list))\n"
    "        prec = total_tp/(total_tp+total_fp) if (total_tp+total_fp)>0 else 0.0\n"
    "        rec  = total_tp/(total_tp+total_fn) if (total_tp+total_fn)>0 else 0.0\n"
    "        row  = {'model': model_name, 'threshold': tau,\n"
    "                'macro_f05': round(macro_f05,4),\n"
    "                'precision': round(prec,4), 'recall': round(rec,4),\n"
    "                'false_positives': total_fp, 'false_negatives': total_fn,\n"
    "                'avg_matches_per_s1': round(total_preds/len(val_gt),3),\n"
    "                'n_val_s1_evaluated': len(val_gt)}\n"
    "        results.append(row)\n"
    "        if macro_f05 > best_f05:\n"
    "            best_f05, best_row = macro_f05, row\n"
    "    return pd.DataFrame(results), best_row\n"
    "\n"
    "lr_df,  lr_best  = evaluate_threshold_grid(lr_val_probs,  'LogisticRegression')\n"
    "xgb_df, xgb_best = evaluate_threshold_grid(xgb_val_probs, 'XGBoost')\n"
    "\n"
    "lr_roc  = roc_auc_score(y_val, lr_val_probs)\n"
    "lr_pr   = average_precision_score(y_val, lr_val_probs)\n"
    "xgb_roc = roc_auc_score(y_val, xgb_val_probs)\n"
    "xgb_pr  = average_precision_score(y_val, xgb_val_probs)\n"
    "lr_f1   = f1_score(y_val, (lr_val_probs  >= lr_best['threshold']).astype(int))\n"
    "xgb_f1  = f1_score(y_val, (xgb_val_probs >= xgb_best['threshold']).astype(int))\n"
    "\n"
    "comp_summary = pd.DataFrame([\n"
    "    {'Model':'Logistic Regression','Optimal tau*':lr_best['threshold'],\n"
    "     'Macro F0.5':lr_best['macro_f05'],'Precision':lr_best['precision'],\n"
    "     'Recall':lr_best['recall'],'F1':round(lr_f1,4),\n"
    "     'ROC-AUC':round(lr_roc,4),'PR-AUC':round(lr_pr,4),\n"
    "     'Val S1 Evaluated':lr_best['n_val_s1_evaluated'],\n"
    "     'Train Time':f'{lr_time:.2f}s'},\n"
    "    {'Model':'XGBoost','Optimal tau*':xgb_best['threshold'],\n"
    "     'Macro F0.5':xgb_best['macro_f05'],'Precision':xgb_best['precision'],\n"
    "     'Recall':xgb_best['recall'],'F1':round(xgb_f1,4),\n"
    "     'ROC-AUC':round(xgb_roc,4),'PR-AUC':round(xgb_pr,4),\n"
    "     'Val S1 Evaluated':xgb_best['n_val_s1_evaluated'],\n"
    "     'Train Time':f'{xgb_time:.2f}s'},\n"
    "])\n"
    "print('=' * 80)\n"
    "print('FINAL VALIDATION MODEL COMPARISON (Exact Macro F0.5, threshold on val only)')\n"
    "print('=' * 80)\n"
    "display(comp_summary)\n"
))

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print('Sections 11-14 appended.')
