import json, os

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

# ─────────────────────────────────────────────────────────────────────────────
# FIX 1 — Cell 18: replace full .df() negative pool with 3-pass chunked approach
# ─────────────────────────────────────────────────────────────────────────────
assert NB['cells'][18]['cell_type'] == 'code'
assert 'df_neg_pool' in NB['cells'][18]['source']

NB['cells'][18]['source'] = (
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE labeled_topk AS\n"
    "SELECT c.*,\n"
    "    case when g.target_id is not null then 1 else 0 end as label\n"
    "FROM topk_candidates c\n"
    "LEFT JOIN (\n"
    "    SELECT entity_id as s1_id, unnest(string_split(matched_entity_ids,',')) as target_id\n"
    "    FROM s1_gt WHERE matched_entity_ids is not null\n"
    ") g ON c.s1_id=g.s1_id AND c.target_id=g.target_id;\n"
    "\"\"\")\n"
    "\n"
    "label_dist = con.execute(\"\"\"\n"
    "    SELECT split, label, count(*) as pair_count\n"
    "    FROM labeled_topk GROUP BY split,label ORDER BY split,label\n"
    "\"\"\").df()\n"
    "print('Raw Candidate Label Distribution:')\n"
    "display(label_dist)\n"
    "\n"
    "train_pos_cnt   = con.execute(\"SELECT count(*) FROM labeled_topk WHERE split='train' AND label=1\").fetchone()[0]\n"
    "total_neg_pool  = con.execute(\"SELECT count(*) FROM labeled_topk WHERE split='train' AND label=0\").fetchone()[0]\n"
    "max_train_negs  = int(train_pos_cnt * HARD_NEG_RATIO)\n"
    "HARD_NEG_CHUNK_SIZE = 50000\n"
    "\n"
    "print(f'Positives (train):      {train_pos_cnt:,}')\n"
    "print(f'Negative pool (train):  {total_neg_pool:,}')\n"
    "print(f'Target negatives:       {max_train_negs:,}  (ratio {HARD_NEG_RATIO})')\n"
    "print(f'Hard-neg chunk size:    {HARD_NEG_CHUNK_SIZE:,}')\n"
    "\n"
    "from rapidfuzz import fuzz as _fuzz\n"
    "\n"
    "CATEGORIES = [\n"
    "    'high_name_low_addr',\n"
    "    'high_addr_low_name',\n"
    "    'high_name_conflict_door',\n"
    "    'high_addr_diff_name',\n"
    "    'generic_name_collision',\n"
    "    'remaining_difficult',\n"
    "]\n"
    "\n"
    "def _assign_category(ns, as_, s1d, td, s1n):\n"
    "    if ns >= 80 and as_ < 40:                        return 'high_name_low_addr'\n"
    "    elif as_ >= 75 and ns < 40:                      return 'high_addr_low_name'\n"
    "    elif ns >= 70 and s1d and td and s1d != td:      return 'high_name_conflict_door'\n"
    "    elif as_ >= 70 and ns < 60:                      return 'high_addr_diff_name'\n"
    "    elif len(s1n.replace(' ','')) <= 5:              return 'generic_name_collision'\n"
    "    else:                                            return 'remaining_difficult'\n"
    "\n"
    "NEG_COLS = ('s1_id, target_id, pass_count, split, s1_country, s1_raw_name, s1_raw_addr,'\n"
    "            ' s1_norm_name, s1_norm_addr, s1_postal, s1_door,'\n"
    "            ' t_country, t_raw_name, t_raw_addr, t_norm_name, t_norm_addr, t_postal, t_door,'\n"
    "            ' jaccard_score, candidate_rank')\n"
    "NEG_QUERY = f\"SELECT {NEG_COLS} FROM labeled_topk WHERE split='train' AND label=0\"\n"
    "n_neg_chunks = (total_neg_pool + HARD_NEG_CHUNK_SIZE - 1) // HARD_NEG_CHUNK_SIZE\n"
    "\n"
    "# ── PASS 1: count category frequencies ────────────────────────────────────\n"
    "print('\\nPass 1/3: counting hard-negative categories...')\n"
    "cat_counts = {c: 0 for c in CATEGORIES}\n"
    "for ci in range(n_neg_chunks):\n"
    "    chunk = con.execute(\n"
    "        f'{NEG_QUERY} LIMIT {HARD_NEG_CHUNK_SIZE} OFFSET {ci * HARD_NEG_CHUNK_SIZE}'\n"
    "    ).df()\n"
    "    s1n_v = chunk['s1_norm_name'].fillna('').values\n"
    "    tn_v  = chunk['t_norm_name'].fillna('').values\n"
    "    s1a_v = chunk['s1_norm_addr'].fillna('').values\n"
    "    ta_v  = chunk['t_norm_addr'].fillna('').values\n"
    "    s1d_v = chunk['s1_door'].fillna('').values\n"
    "    td_v  = chunk['t_door'].fillna('').values\n"
    "    for i in range(len(chunk)):\n"
    "        ns  = _fuzz.token_sort_ratio(s1n_v[i], tn_v[i])\n"
    "        as_ = _fuzz.token_sort_ratio(s1a_v[i], ta_v[i])\n"
    "        cat_counts[_assign_category(ns, as_, s1d_v[i], td_v[i], s1n_v[i])] += 1\n"
    "    del chunk\n"
    "    gc.collect()\n"
    "\n"
    "print('\\nHard-Negative Category Counts (full pool):')\n"
    "for cat in CATEGORIES:\n"
    "    print(f'  {cat:<30}: {cat_counts[cat]:>8,}')\n"
    "\n"
    "# ── PASS 2: compute per-category sample targets ────────────────────────────\n"
    "print('\\nPass 2/3: computing per-category sample targets...')\n"
    "cat_targets = {}\n"
    "remaining = max_train_negs\n"
    "cats_with_data = [c for c in CATEGORIES if cat_counts[c] > 0]\n"
    "for idx, cat in enumerate(cats_with_data):\n"
    "    if idx == len(cats_with_data) - 1:\n"
    "        share = remaining\n"
    "    else:\n"
    "        share = int(max_train_negs * cat_counts[cat] / total_neg_pool)\n"
    "    share = min(share, cat_counts[cat], remaining)\n"
    "    cat_targets[cat] = share\n"
    "    remaining -= share\n"
    "\n"
    "print('Target samples per category:')\n"
    "for cat in CATEGORIES:\n"
    "    print(f'  {cat:<30}: {cat_targets.get(cat, 0):>8,}')\n"
    "\n"
    "# ── PASS 3: sample and write selected negatives to DuckDB ─────────────────\n"
    "print('\\nPass 3/3: sampling negatives and writing to DuckDB...')\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE hard_negatives_selected (\n"
    "    s1_id VARCHAR, target_id VARCHAR, pass_count BIGINT,\n"
    "    split VARCHAR, s1_country VARCHAR,\n"
    "    s1_raw_name VARCHAR, s1_raw_addr VARCHAR,\n"
    "    s1_norm_name VARCHAR, s1_norm_addr VARCHAR,\n"
    "    s1_postal VARCHAR, s1_door VARCHAR,\n"
    "    t_country VARCHAR,\n"
    "    t_raw_name VARCHAR, t_raw_addr VARCHAR,\n"
    "    t_norm_name VARCHAR, t_norm_addr VARCHAR,\n"
    "    t_postal VARCHAR, t_door VARCHAR,\n"
    "    jaccard_score DOUBLE, candidate_rank BIGINT\n"
    ");\n"
    "\"\"\")\n"
    "\n"
    "cat_filled   = {c: 0 for c in CATEGORIES}\n"
    "total_written = 0\n"
    "rng = __import__('numpy').random.default_rng(SEED)\n"
    "\n"
    "for ci in range(n_neg_chunks):\n"
    "    chunk = con.execute(\n"
    "        f'{NEG_QUERY} LIMIT {HARD_NEG_CHUNK_SIZE} OFFSET {ci * HARD_NEG_CHUNK_SIZE}'\n"
    "    ).df()\n"
    "    s1n_v = chunk['s1_norm_name'].fillna('').values\n"
    "    tn_v  = chunk['t_norm_name'].fillna('').values\n"
    "    s1a_v = chunk['s1_norm_addr'].fillna('').values\n"
    "    ta_v  = chunk['t_norm_addr'].fillna('').values\n"
    "    s1d_v = chunk['s1_door'].fillna('').values\n"
    "    td_v  = chunk['t_door'].fillna('').values\n"
    "\n"
    "    chunk_cats = []\n"
    "    for i in range(len(chunk)):\n"
    "        ns  = _fuzz.token_sort_ratio(s1n_v[i], tn_v[i])\n"
    "        as_ = _fuzz.token_sort_ratio(s1a_v[i], ta_v[i])\n"
    "        chunk_cats.append(_assign_category(ns, as_, s1d_v[i], td_v[i], s1n_v[i]))\n"
    "    chunk['_cat'] = chunk_cats\n"
    "\n"
    "    rows_to_insert = []\n"
    "    for cat in CATEGORIES:\n"
    "        need = cat_targets.get(cat, 0) - cat_filled[cat]\n"
    "        if need <= 0:\n"
    "            continue\n"
    "        cat_rows = chunk[chunk['_cat'] == cat]\n"
    "        if len(cat_rows) == 0:\n"
    "            continue\n"
    "        # Proportional share of this category's budget from this chunk\n"
    "        chunk_share = min(need,\n"
    "                          max(1, int(cat_targets.get(cat, 0) * len(cat_rows) / max(cat_counts[cat], 1))))\n"
    "        chunk_share = min(chunk_share, len(cat_rows), need)\n"
    "        if chunk_share > 0:\n"
    "            sampled = cat_rows.sample(n=chunk_share,\n"
    "                                      random_state=int(rng.integers(0, 2**31)))\n"
    "            rows_to_insert.append(sampled.drop(columns=['_cat']))\n"
    "            cat_filled[cat] += chunk_share\n"
    "\n"
    "    if rows_to_insert:\n"
    "        batch = __import__('pandas').concat(rows_to_insert, ignore_index=True)\n"
    "        con.register('_neg_batch', batch)\n"
    "        con.execute('INSERT INTO hard_negatives_selected SELECT * FROM _neg_batch')\n"
    "        total_written += len(batch)\n"
    "        del batch\n"
    "\n"
    "    del chunk, rows_to_insert\n"
    "    gc.collect()\n"
    "\n"
    "# ── REPORT ────────────────────────────────────────────────────────────────\n"
    "final_neg_cnt = con.execute('SELECT count(*) FROM hard_negatives_selected').fetchone()[0]\n"
    "print('\\nSampled Hard-Negative Counts by Category:')\n"
    "for cat in CATEGORIES:\n"
    "    print(f'  {cat:<30}: {cat_filled[cat]:>8,}')\n"
    "print(f'  {\"TOTAL\":<30}: {final_neg_cnt:>8,}')\n"
    "\n"
    "assert final_neg_cnt <= train_pos_cnt * HARD_NEG_RATIO + 1, \\\n"
    "    f'HARD NEG ERROR: {final_neg_cnt} > {train_pos_cnt} * {HARD_NEG_RATIO}'\n"
    "print(f'  [PASS] Neg/Pos ratio: {final_neg_cnt/train_pos_cnt:.3f} (target {HARD_NEG_RATIO})')\n"
    "\n"
    "try:\n"
    "    import psutil\n"
    "    print(f'  Process RAM: {psutil.Process().memory_info().rss/1024/1024:.1f}MB')\n"
    "except ImportError:\n"
    "    pass\n"
    "\n"
    "# ── BUILD train_pairs_selected IN DUCKDB (no pandas) ──────────────────────\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE train_pairs_selected AS\n"
    "SELECT s1_id, target_id, pass_count, split, s1_country, s1_raw_name, s1_raw_addr,\n"
    "       s1_norm_name, s1_norm_addr, s1_postal, s1_door,\n"
    "       t_country, t_raw_name, t_raw_addr, t_norm_name, t_norm_addr, t_postal, t_door,\n"
    "       jaccard_score, candidate_rank, 1 as label\n"
    "FROM labeled_topk WHERE split='train' AND label=1\n"
    "UNION ALL\n"
    "SELECT s1_id, target_id, pass_count, split, s1_country, s1_raw_name, s1_raw_addr,\n"
    "       s1_norm_name, s1_norm_addr, s1_postal, s1_door,\n"
    "       t_country, t_raw_name, t_raw_addr, t_norm_name, t_norm_addr, t_postal, t_door,\n"
    "       jaccard_score, candidate_rank, 0 as label\n"
    "FROM hard_negatives_selected;\n"
    "\"\"\")\n"
    "\n"
    "final_train_cnt = con.execute('SELECT count(*) FROM train_pairs_selected').fetchone()[0]\n"
    "print(f'\\nBalanced Training Set:')\n"
    "print(f'  Positive Pairs:  {train_pos_cnt:,}')\n"
    "print(f'  Hard Negatives:  {final_neg_cnt:,}')\n"
    "print(f'  Ratio (Neg:Pos): {final_neg_cnt/train_pos_cnt:.2f}:1')\n"
    "print(f'  Total Pairs:     {final_train_cnt:,}')\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# FIX 2 — Cell 22: LR memory note + XGBoost n_jobs=4
# ─────────────────────────────────────────────────────────────────────────────
assert NB['cells'][22]['cell_type'] == 'code'
src22 = NB['cells'][22]['source']

OLD_LR = (
    "scaler = StandardScaler()\n"
    "X_train_sc = scaler.fit_transform(X_train)\n"
    "X_val_sc   = scaler.transform(X_val)\n"
)
NEW_LR = (
    "scaler = StandardScaler()\n"
    "# fit_transform creates a float64 copy of X_train internally.\n"
    "# Additional RAM = X_train rows x N_FEAT x 8 bytes (float64)\n"
    "_lr_extra_mb = X_train.shape[0] * X_train.shape[1] * 8 / 1024 / 1024\n"
    "print(f'  LR scaler: fit_transform will use ~{_lr_extra_mb:.1f}MB extra (float64 copy)')\n"
    "X_train_sc = scaler.fit_transform(X_train)\n"
    "X_val_sc   = scaler.transform(X_val)\n"
)
assert OLD_LR in src22, 'Could not find scaler block in cell 22'
src22 = src22.replace(OLD_LR, NEW_LR, 1)

src22 = src22.replace('tree_method=\'hist\', random_state=SEED, n_jobs=8',
                      'tree_method=\'hist\', random_state=SEED, n_jobs=4')
NB['cells'][22]['source'] = src22

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print('All fixes applied.')
