"""Append strategy E: char n-gram TF-IDF sparse retrieval."""
import json

NB = r'c:\Users\akash\OneDrive\Desktop\Amazon ML Challenge\notebooks\train_matching_model_colab.ipynb'

with open(NB, 'r', encoding='utf-8') as f:
    nb = json.load(f)

def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

src_e = (
"# ── Strategy E: char 3/4-gram TF-IDF sparse retrieval, K=50 ─────────────\n"
"# Process country-by-country. For each country:\n"
"#   1. Build TF-IDF matrix on target_pool names (char 3-4 gram)\n"
"#   2. Query with S1 names, get top-N cosine matches per S1\n"
"#   3. Insert (s1_id, target_id) pairs into raw_cands_E\n"
"# No full Cartesian product. Sparse matrix per country only.\n"
"print('Strategy E: char n-gram TF-IDF sparse retrieval, K=50...')\n"
"t0 = time.time(); m0 = _mem_mb()\n"
"K_E = 50\n"
"NGRAM_TOP_N = 30  # top-N per S1 from TF-IDF before merging with SQL passes\n"
"\n"
"from sklearn.feature_extraction.text import TfidfVectorizer\n"
"from sklearn.preprocessing import normalize\n"
"import scipy.sparse as sp\n"
"\n"
"# Create staging table for n-gram candidates\n"
"con.execute(\"\"\"\n"
"CREATE OR REPLACE TABLE ngram_cands_E (\n"
"    s1_id VARCHAR, target_id VARCHAR, ngram_score FLOAT\n"
");\n"
"\"\"\")\n"
"\n"
"countries = [r[0] for r in con.execute(\n"
"    \"SELECT DISTINCT country FROM s1_split ORDER BY country\"\n"
").fetchall()]\n"
"print(f'  Processing {len(countries)} countries...')\n"
"\n"
"NGRAM_CHUNK = 5000  # S1 query chunk per country\n"
"total_ngram_pairs = 0\n"
"\n"
"for ctry in countries:\n"
"    # Load target pool names for this country\n"
"    tgt_df = con.execute(f\"\"\"\n"
"        SELECT entity_id, coalesce(norm_name,'') as name\n"
"        FROM target_pool WHERE country='{ctry}'\n"
"    \"\"\").df()\n"
"    if len(tgt_df) < 2:\n"
"        del tgt_df; gc.collect(); continue\n"
"\n"
"    # Fit TF-IDF on target names (char 3-4 gram)\n"
"    vec = TfidfVectorizer(analyzer='char_wb', ngram_range=(3,4),\n"
"                          min_df=1, max_features=50000, sublinear_tf=True)\n"
"    try:\n"
"        T = vec.fit_transform(tgt_df['name'].tolist())\n"
"    except Exception:\n"
"        del tgt_df; gc.collect(); continue\n"
"    T = normalize(T, norm='l2', copy=False)\n"
"    tgt_ids = tgt_df['entity_id'].values\n"
"    del tgt_df; gc.collect()\n"
"\n"
"    # Load S1 entities for this country in chunks\n"
"    s1_ctry = con.execute(f\"\"\"\n"
"        SELECT entity_id, coalesce(norm_name,'') as name\n"
"        FROM s1_split WHERE country='{ctry}'\n"
"    \"\"\").df()\n"
"    if len(s1_ctry) == 0:\n"
"        del s1_ctry, T, tgt_ids; gc.collect(); continue\n"
"\n"
"    n_s1_ctry = len(s1_ctry)\n"
"    n_chunks_e = (n_s1_ctry + NGRAM_CHUNK - 1) // NGRAM_CHUNK\n"
"    ctry_pairs = 0\n"
"\n"
"    for ci in range(n_chunks_e):\n"
"        s1_chunk = s1_ctry.iloc[ci*NGRAM_CHUNK:(ci+1)*NGRAM_CHUNK]\n"
"        Q = vec.transform(s1_chunk['name'].tolist())\n"
"        Q = normalize(Q, norm='l2', copy=False)\n"
"        # Cosine similarity: Q x T^T  (sparse x sparse)\n"
"        scores = (Q @ T.T).toarray()  # shape: (chunk_s1, n_tgt)\n"
"        # For each S1 get top NGRAM_TOP_N targets\n"
"        rows_out = []\n"
"        for qi in range(scores.shape[0]):\n"
"            top_idx = np.argpartition(scores[qi], -min(NGRAM_TOP_N, scores.shape[1]))[-min(NGRAM_TOP_N, scores.shape[1]):]\n"
"            for ti in top_idx:\n"
"                sc = float(scores[qi, ti])\n"
"                if sc > 0.05:  # skip near-zero matches\n"
"                    rows_out.append((s1_chunk.iloc[qi]['entity_id'], tgt_ids[ti], sc))\n"
"        if rows_out:\n"
"            batch = pd.DataFrame(rows_out, columns=['s1_id','target_id','ngram_score'])\n"
"            con.register('_ng_batch', batch)\n"
"            con.execute('INSERT INTO ngram_cands_E SELECT * FROM _ng_batch')\n"
"            ctry_pairs += len(rows_out)\n"
"            del batch\n"
"        del Q, scores, rows_out\n"
"        gc.collect()\n"
"\n"
"    total_ngram_pairs += ctry_pairs\n"
"    del s1_ctry, T, tgt_ids, vec\n"
"    gc.collect()\n"
"\n"
"print(f'  N-gram candidate pairs inserted: {total_ngram_pairs:,}')\n"
"\n"
"# Merge n-gram candidates with strategy D raw pairs\n"
"con.execute(\"\"\"\n"
"CREATE OR REPLACE TABLE raw_cands_E AS\n"
"SELECT s1_id, target_id, max(pass_count) as pass_count\n"
"FROM (\n"
"    SELECT s1_id, target_id, pass_count FROM raw_cands_D\n"
"    UNION ALL\n"
"    SELECT s1_id, target_id, 1 as pass_count FROM ngram_cands_E\n"
") sub\n"
"GROUP BY s1_id, target_id;\n"
"\"\"\")\n"
"raw_e = con.execute('SELECT count(*) FROM raw_cands_E').fetchone()[0]\n"
"print(f'  Raw pairs E (D + n-gram): {raw_e:,}')\n"
"\n"
"# Rank to K_E\n"
"con.execute('CREATE OR REPLACE TABLE topk_E (s1_id VARCHAR, target_id VARCHAR, pass_count BIGINT,'\n"
"            ' split VARCHAR, s1_country VARCHAR,'\n"
"            ' s1_raw_name VARCHAR, s1_raw_addr VARCHAR,'\n"
"            ' s1_norm_name VARCHAR, s1_norm_addr VARCHAR,'\n"
"            ' s1_postal VARCHAR, s1_door VARCHAR,'\n"
"            ' t_country VARCHAR, t_raw_name VARCHAR, t_raw_addr VARCHAR,'\n"
"            ' t_norm_name VARCHAR, t_norm_addr VARCHAR,'\n"
"            ' t_postal VARCHAR, t_door VARCHAR,'\n"
"            ' jaccard_score DOUBLE, candidate_rank BIGINT);')\n"
"s1_ids_e = [r[0] for r in con.execute('SELECT DISTINCT s1_id FROM raw_cands_E ORDER BY s1_id').fetchall()]\n"
"n_chunks_e2 = (len(s1_ids_e) + RANK_CHUNK_SIZE - 1) // RANK_CHUNK_SIZE\n"
"for ci in range(n_chunks_e2):\n"
"    chunk = s1_ids_e[ci*RANK_CHUNK_SIZE:(ci+1)*RANK_CHUNK_SIZE]\n"
"    con.register('_cids', pd.DataFrame({'s1_id': chunk}))\n"
"    con.execute(f\"\"\"\n"
"    INSERT INTO topk_E\n"
"    SELECT s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,\n"
"           s1_norm_name,s1_norm_addr,s1_postal,s1_door,t_country,t_raw_name,t_raw_addr,\n"
"           t_norm_name,t_norm_addr,t_postal,t_door,jaccard_score,candidate_rank\n"
"    FROM (\n"
"        SELECT c.s1_id,c.target_id,c.pass_count,s.split,s.country AS s1_country,\n"
"               s.raw_name AS s1_raw_name,s.raw_addr AS s1_raw_addr,\n"
"               s.norm_name AS s1_norm_name,s.norm_addr AS s1_norm_addr,\n"
"               s.postal AS s1_postal,s.door AS s1_door,\n"
"               t.country AS t_country,t.raw_name AS t_raw_name,t.raw_addr AS t_raw_addr,\n"
"               t.norm_name AS t_norm_name,t.norm_addr AS t_norm_addr,\n"
"               t.postal AS t_postal,t.door AS t_door,\n"
"               (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float/\n"
"                     nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0))+\n"
"                0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float/\n"
"                     nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0)))\n"
"               AS jaccard_score,\n"
"               row_number() OVER (PARTITION BY c.s1_id ORDER BY\n"
"                   (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float/\n"
"                         nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0))+\n"
"                    0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float/\n"
"                         nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0))) DESC,\n"
"                   c.pass_count DESC) AS candidate_rank\n"
"        FROM raw_cands_E c\n"
"        JOIN _cids x ON c.s1_id=x.s1_id\n"
"        JOIN s1_split s ON c.s1_id=s.entity_id\n"
"        JOIN target_pool t ON c.target_id=t.entity_id\n"
"    ) ranked WHERE candidate_rank <= {K_E};\n"
"    \"\"\")\n"
"tot,s1s,avg,p95 = _cand_stats(con,'topk_E')\n"
"r25 = _recall_at_k(con,'topk_E',25,val_gt)\n"
"r50 = _recall_at_k(con,'topk_E',50,val_gt)\n"
"blocking_results.append({\n"
"    'strategy':'E_8pass_perm_ngram_K50','K':50,\n"
"    'candidate_pairs':tot,'avg_cands':round(avg,1),'p95_cands':p95,\n"
"    'recall_at_25':round(r25,4),'recall_at_50':round(r50,4),'recall_at_100':round(r50,4),\n"
"    'runtime_s':round(time.time()-t0,1),'peak_mem_mb':round(_mem_mb()-m0,1)\n"
"})\n"
"print(f'  pairs={tot:,}  avg={avg:.1f}  p95={p95}  recall@25={r25:.4f}  recall@50={r50:.4f}')\n"
"gc.collect()\n"
)

nb['cells'].append(code(src_e))

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
print(f'Cells: {len(nb["cells"])}  Part4b written.')
