import json, os

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

SMOKE_MD = md(
    "### Section 7b: Smoke Test — Chunked Ranking Validation (TEST_S1 = 10,000)\n\n"
    "Before running the full 150k experiment, validate the chunked ranking architecture:\n"
    "- Raw candidate count for 10k S1 subset\n"
    "- Top-K candidate count (must be <= 10,000 x 25 = 250,000)\n"
    "- Average candidates per S1\n"
    "- No duplicate (s1_id, target_id) pairs in topk_candidates\n"
    "- Every retained candidate came from raw_candidate_pairs\n\n"
    "**Run this cell first. Only proceed to Section 8 after all checks pass.**\n"
)

SMOKE_CODE = code(
    "TEST_S1 = 10000\n"
    "print('=' * 60)\n"
    "print(f'SMOKE TEST: Chunked Ranking on {TEST_S1:,} S1 entities')\n"
    "print('=' * 60)\n\n"
    "# Sample TEST_S1 S1 IDs from the full s1_split\n"
    "test_s1_ids = [r[0] for r in con.execute(f\"\"\"\n"
    "    SELECT entity_id FROM s1_split\n"
    "    USING SAMPLE {TEST_S1} (reservoir, {SEED})\n"
    "\"\"\").fetchall()]\n"
    "print(f'Test S1 sample size: {len(test_s1_ids):,}')\n\n"
    "# Count raw candidates for this subset\n"
    "con.register('test_s1_ids_df', __import__('pandas').DataFrame({'s1_id': test_s1_ids}))\n"
    "test_raw_cnt = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM raw_candidate_pairs\n"
    "    WHERE s1_id IN (SELECT s1_id FROM test_s1_ids_df)\n"
    "\"\"\").fetchone()[0]\n"
    "print(f'Raw candidates for test subset: {test_raw_cnt:,}')\n"
    "print(f'Avg raw candidates/S1: {test_raw_cnt/len(test_s1_ids):.1f}')\n\n"
    "# Run chunked ranking on test subset only\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE topk_smoke_test (\n"
    "    s1_id VARCHAR, target_id VARCHAR, pass_count BIGINT,\n"
    "    split VARCHAR, s1_country VARCHAR,\n"
    "    s1_raw_name VARCHAR, s1_raw_addr VARCHAR,\n"
    "    s1_norm_name VARCHAR, s1_norm_addr VARCHAR,\n"
    "    s1_postal VARCHAR, s1_door VARCHAR,\n"
    "    t_country VARCHAR,\n"
    "    t_raw_name VARCHAR, t_raw_addr VARCHAR,\n"
    "    t_norm_name VARCHAR, t_norm_addr VARCHAR,\n"
    "    t_postal VARCHAR, t_door VARCHAR,\n"
    "    jaccard_score DOUBLE, candidate_rank BIGINT\n"
    ");\n"
    "\"\"\")\n\n"
    "SMOKE_CHUNK = 10000\n"
    "smoke_chunks = (len(test_s1_ids) + SMOKE_CHUNK - 1) // SMOKE_CHUNK\n"
    "smoke_written = 0\n"
    "import pandas as _pd\n\n"
    "for ci in range(smoke_chunks):\n"
    "    chunk = test_s1_ids[ci * SMOKE_CHUNK : (ci + 1) * SMOKE_CHUNK]\n"
    "    con.register('smoke_chunk_ids', _pd.DataFrame({'s1_id': chunk}))\n"
    "    con.execute(f\"\"\"\n"
    "    INSERT INTO topk_smoke_test\n"
    "    SELECT s1_id, target_id, pass_count,\n"
    "           split, s1_country,\n"
    "           s1_raw_name, s1_raw_addr,\n"
    "           s1_norm_name, s1_norm_addr,\n"
    "           s1_postal, s1_door,\n"
    "           t_country,\n"
    "           t_raw_name, t_raw_addr,\n"
    "           t_norm_name, t_norm_addr,\n"
    "           t_postal, t_door,\n"
    "           jaccard_score, candidate_rank\n"
    "    FROM (\n"
    "        SELECT\n"
    "            c.s1_id, c.target_id, c.pass_count,\n"
    "            s.split, s.country AS s1_country,\n"
    "            s.raw_name AS s1_raw_name, s.raw_addr AS s1_raw_addr,\n"
    "            s.norm_name AS s1_norm_name, s.norm_addr AS s1_norm_addr,\n"
    "            s.postal AS s1_postal, s.door AS s1_door,\n"
    "            t.country AS t_country,\n"
    "            t.raw_name AS t_raw_name, t.raw_addr AS t_raw_addr,\n"
    "            t.norm_name AS t_norm_name, t.norm_addr AS t_norm_addr,\n"
    "            t.postal AS t_postal, t.door AS t_door,\n"
    "            (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float /\n"
    "                  nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0)) +\n"
    "             0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float /\n"
    "                  nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0)))\n"
    "                AS jaccard_score,\n"
    "            row_number() OVER (\n"
    "                PARTITION BY c.s1_id\n"
    "                ORDER BY (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float /\n"
    "                               nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0)) +\n"
    "                          0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float /\n"
    "                               nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0))) DESC,\n"
    "                c.pass_count DESC\n"
    "            ) AS candidate_rank\n"
    "        FROM raw_candidate_pairs c\n"
    "        JOIN smoke_chunk_ids     x ON c.s1_id = x.s1_id\n"
    "        JOIN s1_split            s ON c.s1_id = s.entity_id\n"
    "        JOIN target_pool         t ON c.target_id = t.entity_id\n"
    "    ) ranked\n"
    "    WHERE candidate_rank <= {TOP_K};\n"
    "    \"\"\")\n"
    "    smoke_written = con.execute('SELECT count(*) FROM topk_smoke_test').fetchone()[0]\n\n"
    "# ── SMOKE TEST CHECKS ─────────────────────────────────────────────────────\n"
    "print('\\nSmoke Test Checks:')\n"
    "all_ok = True\n\n"
    "# 1. Row count within theoretical max\n"
    "max_possible = TOP_K * len(test_s1_ids)\n"
    "ok1 = smoke_written <= max_possible\n"
    "print(f'  [{\"PASS\" if ok1 else \"FAIL\"}] Row count: {smoke_written:,} <= max {max_possible:,}')\n"
    "if not ok1: all_ok = False\n\n"
    "# 2. No duplicate (s1_id, target_id) pairs\n"
    "dup_pairs = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM (\n"
    "        SELECT s1_id, target_id, count(*) as n\n"
    "        FROM topk_smoke_test GROUP BY s1_id, target_id HAVING n > 1\n"
    "    )\n"
    "\"\"\").fetchone()[0]\n"
    "ok2 = dup_pairs == 0\n"
    "print(f'  [{\"PASS\" if ok2 else \"FAIL\"}] Duplicate (s1_id, target_id) pairs: {dup_pairs}')\n"
    "if not ok2: all_ok = False\n\n"
    "# 3. Every retained candidate came from raw_candidate_pairs\n"
    "orphan_cnt = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM topk_smoke_test tk\n"
    "    WHERE NOT EXISTS (\n"
    "        SELECT 1 FROM raw_candidate_pairs r\n"
    "        WHERE r.s1_id = tk.s1_id AND r.target_id = tk.target_id\n"
    "    )\n"
    "\"\"\").fetchone()[0]\n"
    "ok3 = orphan_cnt == 0\n"
    "print(f'  [{\"PASS\" if ok3 else \"FAIL\"}] Candidates not in raw pairs (orphans): {orphan_cnt}')\n"
    "if not ok3: all_ok = False\n\n"
    "# 4. candidate_rank <= TOP_K for all rows\n"
    "over_k = con.execute(f'SELECT count(*) FROM topk_smoke_test WHERE candidate_rank > {TOP_K}').fetchone()[0]\n"
    "ok4 = over_k == 0\n"
    "print(f'  [{\"PASS\" if ok4 else \"FAIL\"}] Rows with candidate_rank > {TOP_K}: {over_k}')\n"
    "if not ok4: all_ok = False\n\n"
    "# 5. Per-S1 stats\n"
    "smoke_per_s1 = [r[0] for r in con.execute('SELECT count(*) FROM topk_smoke_test GROUP BY s1_id').fetchall()]\n"
    "print(f'  Avg candidates/S1: {sum(smoke_per_s1)/len(smoke_per_s1):.1f}')\n"
    "print(f'  Max candidates/S1: {max(smoke_per_s1)}')\n\n"
    "if not all_ok:\n"
    "    raise AssertionError('SMOKE TEST FAILED. Fix chunked ranking before running full experiment.')\n"
    "print('\\nAll smoke test checks passed. Proceed to full 150k experiment (Section 8+).')\n"
    "con.execute('DROP TABLE IF EXISTS topk_smoke_test;')\n"
)

# Insert after cell 14 (index 14), so insert at position 15
NB['cells'].insert(15, SMOKE_CODE)
NB['cells'].insert(15, SMOKE_MD)

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print(f'Smoke test cells inserted. Total cells: {len(NB["cells"])}')
