"""Append Section 22: improved feature extraction from best blocking table."""
import json

NB = r'c:\Users\akash\OneDrive\Desktop\Amazon ML Challenge\notebooks\train_matching_model_colab.ipynb'

with open(NB, 'r', encoding='utf-8') as f:
    nb = json.load(f)

def md(src): return {"cell_type":"markdown","metadata":{},"source":src}
def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

nb['cells'].append(md(
"### Section 22: Improved Feature Extraction (v2) — Best Blocking Table\n\n"
"Reuses the existing 24-feature pipeline and adds 6 candidate-context features:\n"
"- `norm_rank` — rank / K (normalized)\n"
"- `score_margin` — jaccard_score - top_jaccard_score for this S1\n"
"- `top_score` — jaccard_score of rank-1 candidate for this S1\n"
"- `name_addr_composite` — 0.7*name_sort + 0.3*addr_sort\n"
"- `rank_x_jaccard` — candidate_rank * jaccard_score interaction\n"
"- `pass_count_norm` — pass_count / max_pass_count (normalized)\n\n"
"Total: **30 features**. No target leakage — context features use only blocking scores.\n"
))

src_22 = (
"import gc\n"
"from rapidfuzz import fuzz as _fuzz2, distance as _dist2\n"
"\n"
"FEATURE_NAMES_V2 = [\n"
"    # original 24\n"
"    'name_exact_raw','name_exact_norm','name_token_sort_ratio','name_token_set_ratio',\n"
"    'name_jaro_winkler','name_levenshtein_ratio','name_char_sim','name_substring_containment',\n"
"    'addr_exact_norm','addr_token_sort_ratio','addr_token_set_ratio','addr_token_jaccard',\n"
"    'addr_char_sim','addr_num_overlap','addr_postal_match',\n"
"    'country_agreement','s1_name_missing','t_name_missing','s1_addr_missing','t_addr_missing',\n"
"    'candidate_rank','blocking_pass_count','name_x_addr','name_diff_addr',\n"
"    # 6 new context features\n"
"    'norm_rank','score_margin','top_score','name_addr_composite',\n"
"    'rank_x_jaccard','pass_count_norm',\n"
"]\n"
"N_FEAT_V2 = len(FEATURE_NAMES_V2)\n"
"FEATURE_CHUNK_SIZE = 50000\n"
"\n"
"def compute_pair_features_v2(s1_raw,s1_norm,s1_addr,s1_postal,s1_door,\n"
"                              t_raw,t_norm,t_addr,t_postal,t_door,\n"
"                              s1_country,t_country,rank,pass_count,\n"
"                              jaccard_score,top_jac,k_val,max_pass):\n"
"    # original 24 features\n"
"    exact_raw  = 1.0 if s1_raw and s1_raw==t_raw else 0.0\n"
"    exact_norm = 1.0 if s1_norm and s1_norm==t_norm else 0.0\n"
"    name_sort  = _fuzz2.token_sort_ratio(s1_norm,t_norm)/100.0\n"
"    name_set   = _fuzz2.token_set_ratio(s1_norm,t_norm)/100.0\n"
"    jw         = _dist2.JaroWinkler.similarity(s1_norm,t_norm)\n"
"    lev        = _dist2.Levenshtein.normalized_similarity(s1_norm,t_norm)\n"
"    name_char  = _fuzz2.ratio(s1_norm,t_norm)/100.0\n"
"    name_sub   = 1.0 if (s1_norm and t_norm and (s1_norm in t_norm or t_norm in s1_norm)) else 0.0\n"
"    addr_exact = 1.0 if s1_addr and s1_addr==t_addr else 0.0\n"
"    addr_sort  = _fuzz2.token_sort_ratio(s1_addr,t_addr)/100.0\n"
"    addr_set   = _fuzz2.token_set_ratio(s1_addr,t_addr)/100.0\n"
"    s1_at = set(s1_addr.split()) if s1_addr else set()\n"
"    t_at  = set(t_addr.split())  if t_addr  else set()\n"
"    addr_jac   = len(s1_at&t_at)/len(s1_at|t_at) if (s1_at or t_at) else 0.0\n"
"    addr_char  = _fuzz2.ratio(s1_addr,t_addr)/100.0\n"
"    s1_nums = {w for w in s1_at if w.isdigit()}\n"
"    t_nums  = {w for w in t_at  if w.isdigit()}\n"
"    if s1_nums and t_nums:           num_ov = len(s1_nums&t_nums)/len(s1_nums|t_nums)\n"
"    elif not s1_nums and not t_nums: num_ov = 0.5\n"
"    else:                            num_ov = 0.0\n"
"    postal_m   = 1.0 if s1_postal and t_postal and s1_postal==t_postal else 0.0\n"
"    country_ag = 1.0 if s1_country==t_country else 0.0\n"
"    s1nm = 1.0 if not s1_norm else 0.0\n"
"    tnm  = 1.0 if not t_norm  else 0.0\n"
"    s1am = 1.0 if not s1_addr else 0.0\n"
"    tam  = 1.0 if not t_addr  else 0.0\n"
"    rank_f = 1.0/rank if rank>0 else 0.0\n"
"    pc_f   = float(pass_count)\n"
"    nxa    = name_sort*addr_sort\n"
"    nda    = abs(name_sort-addr_sort)\n"
"    # 6 new context features\n"
"    norm_rank_f   = rank / max(k_val, 1)\n"
"    score_margin  = float(jaccard_score) - float(top_jac) if top_jac is not None else 0.0\n"
"    top_score_f   = float(top_jac) if top_jac is not None else 0.0\n"
"    composite     = 0.7*name_sort + 0.3*addr_sort\n"
"    rank_x_jac    = rank_f * float(jaccard_score)\n"
"    pc_norm       = float(pass_count) / max(float(max_pass), 1.0)\n"
"    return [exact_raw,exact_norm,name_sort,name_set,jw,lev,name_char,name_sub,\n"
"            addr_exact,addr_sort,addr_set,addr_jac,addr_char,num_ov,postal_m,\n"
"            country_ag,s1nm,tnm,s1am,tam,rank_f,pc_f,nxa,nda,\n"
"            norm_rank_f,score_margin,top_score_f,composite,rank_x_jac,pc_norm]\n"
"\n"
"def _fill_X_v2(df_chunk, X, y, row_offset, k_val, top_jac_map, max_pass):\n"
"    n = len(df_chunk)\n"
"    s1_raw  = df_chunk['s1_raw_name'].fillna('').values\n"
"    s1_norm = df_chunk['s1_norm_name'].fillna('').values\n"
"    s1_addr = df_chunk['s1_norm_addr'].fillna('').values\n"
"    s1_post = df_chunk['s1_postal'].fillna('').values\n"
"    s1_door = df_chunk['s1_door'].fillna('').values\n"
"    s1_coun = df_chunk['s1_country'].fillna('').values\n"
"    t_raw   = df_chunk['t_raw_name'].fillna('').values\n"
"    t_norm  = df_chunk['t_norm_name'].fillna('').values\n"
"    t_addr  = df_chunk['t_norm_addr'].fillna('').values\n"
"    t_post  = df_chunk['t_postal'].fillna('').values\n"
"    t_door  = df_chunk['t_door'].fillna('').values\n"
"    t_coun  = df_chunk['t_country'].fillna('').values\n"
"    ranks   = df_chunk['candidate_rank'].values\n"
"    passes  = df_chunk['pass_count'].values\n"
"    jacs    = df_chunk['jaccard_score'].fillna(0).values\n"
"    labels  = df_chunk['label'].values\n"
"    s1_ids  = df_chunk['s1_id'].values\n"
"    for i in range(n):\n"
"        sid = s1_ids[i]\n"
"        top_jac = top_jac_map.get(sid, 0.0)\n"
"        X[row_offset+i] = compute_pair_features_v2(\n"
"            str(s1_raw[i] or ''), str(s1_norm[i] or ''), str(s1_addr[i] or ''),\n"
"            str(s1_post[i] or ''), str(s1_door[i] or ''),\n"
"            str(t_raw[i] or ''),  str(t_norm[i] or ''),  str(t_addr[i] or ''),\n"
"            str(t_post[i] or ''), str(t_door[i] or ''),\n"
"            str(s1_coun[i] or ''), str(t_coun[i] or ''),\n"
"            int(ranks[i] or 1), int(passes[i] or 1),\n"
"            float(jacs[i]), top_jac, k_val, max_pass\n"
"        )\n"
"        y[row_offset+i] = int(labels[i])\n"
"\n"
"# ── Determine K and max_pass for best blocking table ──────────────────────\n"
"K_BEST = int(best_blocking['K'])\n"
"max_pass_val = con.execute(f'SELECT max(pass_count) FROM {BEST_TOPK_TABLE}').fetchone()[0] or 1\n"
"\n"
"# Build top-jaccard map per S1 (rank=1 score) — small aggregation, safe\n"
"top_jac_rows = con.execute(f\"\"\"\n"
"    SELECT s1_id, jaccard_score FROM {BEST_TOPK_TABLE}\n"
"    WHERE candidate_rank=1\n"
"\"\"\").fetchall()\n"
"top_jac_map = {r[0]: float(r[1]) for r in top_jac_rows}\n"
"print(f'Top-jaccard map built: {len(top_jac_map):,} S1 entries')\n"
"\n"
"# ── Label best-blocking candidates ────────────────────────────────────────\n"
"con.execute(f\"\"\"\n"
"CREATE OR REPLACE TABLE labeled_best AS\n"
"SELECT c.*,\n"
"    case when g.target_id is not null then 1 else 0 end as label\n"
"FROM {BEST_TOPK_TABLE} c\n"
"LEFT JOIN (\n"
"    SELECT entity_id as s1_id, unnest(string_split(matched_entity_ids,',')) as target_id\n"
"    FROM s1_gt WHERE matched_entity_ids is not null\n"
") g ON c.s1_id=g.s1_id AND c.target_id=g.target_id;\n"
"\"\"\")\n"
"\n"
"# ── Hard negatives for best blocking (reuse same 3-pass approach) ─────────\n"
"print('Building hard negatives for best blocking table...')\n"
"from rapidfuzz import fuzz as _fuzz\n"
"import numpy as _np2\n"
"\n"
"CATEGORIES = [\n"
"    'high_name_low_addr','high_addr_low_name','high_name_conflict_door',\n"
"    'high_addr_diff_name','generic_name_collision','remaining_difficult',\n"
"]\n"
"def _assign_category(ns, as_, s1d, td, s1n):\n"
"    if ns >= 80 and as_ < 40:                        return 'high_name_low_addr'\n"
"    elif as_ >= 75 and ns < 40:                      return 'high_addr_low_name'\n"
"    elif ns >= 70 and s1d and td and s1d != td:      return 'high_name_conflict_door'\n"
"    elif as_ >= 70 and ns < 60:                      return 'high_addr_diff_name'\n"
"    elif len(s1n.replace(' ','')) <= 5:              return 'generic_name_collision'\n"
"    else:                                            return 'remaining_difficult'\n"
"\n"
"train_pos_v2 = con.execute(\"SELECT count(*) FROM labeled_best WHERE split='train' AND label=1\").fetchone()[0]\n"
"total_neg_v2 = con.execute(\"SELECT count(*) FROM labeled_best WHERE split='train' AND label=0\").fetchone()[0]\n"
"max_negs_v2  = int(train_pos_v2 * HARD_NEG_RATIO)\n"
"HARD_NEG_CHUNK_SIZE = 50000\n"
"NEG_COLS_V2 = ('s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,'\n"
"               's1_norm_name,s1_norm_addr,s1_postal,s1_door,'\n"
"               't_country,t_raw_name,t_raw_addr,t_norm_name,t_norm_addr,t_postal,t_door,'\n"
"               'jaccard_score,candidate_rank')\n"
"NEG_Q_V2 = f\"SELECT {NEG_COLS_V2} FROM labeled_best WHERE split='train' AND label=0\"\n"
"n_neg_chunks_v2 = (total_neg_v2 + HARD_NEG_CHUNK_SIZE - 1) // HARD_NEG_CHUNK_SIZE\n"
"\n"
"# Pass 1: count\n"
"cat_counts_v2 = {c: 0 for c in CATEGORIES}\n"
"for ci in range(n_neg_chunks_v2):\n"
"    chunk = con.execute(f'{NEG_Q_V2} LIMIT {HARD_NEG_CHUNK_SIZE} OFFSET {ci*HARD_NEG_CHUNK_SIZE}').df()\n"
"    for i in range(len(chunk)):\n"
"        ns  = _fuzz.token_sort_ratio(str(chunk['s1_norm_name'].iloc[i] or ''), str(chunk['t_norm_name'].iloc[i] or ''))\n"
"        as_ = _fuzz.token_sort_ratio(str(chunk['s1_norm_addr'].iloc[i] or ''), str(chunk['t_norm_addr'].iloc[i] or ''))\n"
"        cat_counts_v2[_assign_category(ns, as_, str(chunk['s1_door'].iloc[i] or ''), str(chunk['t_door'].iloc[i] or ''), str(chunk['s1_norm_name'].iloc[i] or ''))] += 1\n"
"    del chunk; gc.collect()\n"
"\n"
"# Pass 2: targets\n"
"cat_targets_v2 = {}; remaining_v2 = max_negs_v2\n"
"cats_with_data_v2 = [c for c in CATEGORIES if cat_counts_v2[c] > 0]\n"
"for idx, cat in enumerate(cats_with_data_v2):\n"
"    share = remaining_v2 if idx == len(cats_with_data_v2)-1 else int(max_negs_v2 * cat_counts_v2[cat] / max(total_neg_v2,1))\n"
"    share = min(share, cat_counts_v2[cat], remaining_v2)\n"
"    cat_targets_v2[cat] = share; remaining_v2 -= share\n"
"\n"
"# Pass 3: sample\n"
"con.execute(f\"\"\"\n"
"CREATE OR REPLACE TABLE hard_neg_v2 (\n"
"    s1_id VARCHAR, target_id VARCHAR, pass_count BIGINT,\n"
"    split VARCHAR, s1_country VARCHAR,\n"
"    s1_raw_name VARCHAR, s1_raw_addr VARCHAR,\n"
"    s1_norm_name VARCHAR, s1_norm_addr VARCHAR,\n"
"    s1_postal VARCHAR, s1_door VARCHAR,\n"
"    t_country VARCHAR, t_raw_name VARCHAR, t_raw_addr VARCHAR,\n"
"    t_norm_name VARCHAR, t_norm_addr VARCHAR,\n"
"    t_postal VARCHAR, t_door VARCHAR,\n"
"    jaccard_score DOUBLE, candidate_rank BIGINT\n"
");\n"
"\"\"\")\n"
"cat_filled_v2 = {c: 0 for c in CATEGORIES}\n"
"rng_v2 = _np2.random.default_rng(SEED)\n"
"import pandas as _pd_v2\n"
"for ci in range(n_neg_chunks_v2):\n"
"    chunk = con.execute(f'{NEG_Q_V2} LIMIT {HARD_NEG_CHUNK_SIZE} OFFSET {ci*HARD_NEG_CHUNK_SIZE}').df()\n"
"    chunk_cats = []\n"
"    for i in range(len(chunk)):\n"
"        ns  = _fuzz.token_sort_ratio(str(chunk['s1_norm_name'].iloc[i] or ''), str(chunk['t_norm_name'].iloc[i] or ''))\n"
"        as_ = _fuzz.token_sort_ratio(str(chunk['s1_norm_addr'].iloc[i] or ''), str(chunk['t_norm_addr'].iloc[i] or ''))\n"
"        chunk_cats.append(_assign_category(ns, as_, str(chunk['s1_door'].iloc[i] or ''), str(chunk['t_door'].iloc[i] or ''), str(chunk['s1_norm_name'].iloc[i] or '')))\n"
"    chunk['_cat'] = chunk_cats\n"
"    rows_to_insert = []\n"
"    for cat in CATEGORIES:\n"
"        need = cat_targets_v2.get(cat,0) - cat_filled_v2[cat]\n"
"        if need <= 0: continue\n"
"        cat_rows = chunk[chunk['_cat']==cat]\n"
"        if len(cat_rows) == 0: continue\n"
"        share = min(need, max(1, int(cat_targets_v2.get(cat,0)*len(cat_rows)/max(cat_counts_v2[cat],1))), len(cat_rows), need)\n"
"        if share > 0:\n"
"            sampled = cat_rows.sample(n=share, random_state=int(rng_v2.integers(0,2**31)))\n"
"            rows_to_insert.append(sampled.drop(columns=['_cat']))\n"
"            cat_filled_v2[cat] += share\n"
"    if rows_to_insert:\n"
"        batch = _pd_v2.concat(rows_to_insert, ignore_index=True)\n"
"        con.register('_neg_v2', batch)\n"
"        con.execute('INSERT INTO hard_neg_v2 SELECT * FROM _neg_v2')\n"
"        del batch\n"
"    del chunk, rows_to_insert; gc.collect()\n"
"\n"
"final_neg_v2 = con.execute('SELECT count(*) FROM hard_neg_v2').fetchone()[0]\n"
"print(f'Hard negatives v2: {final_neg_v2:,}  pos: {train_pos_v2:,}  ratio: {final_neg_v2/max(train_pos_v2,1):.2f}')\n"
"\n"
"con.execute(\"\"\"\n"
"CREATE OR REPLACE TABLE train_v2 AS\n"
"SELECT s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,\n"
"       s1_norm_name,s1_norm_addr,s1_postal,s1_door,\n"
"       t_country,t_raw_name,t_raw_addr,t_norm_name,t_norm_addr,t_postal,t_door,\n"
"       jaccard_score,candidate_rank,1 as label\n"
"FROM labeled_best WHERE split='train' AND label=1\n"
"UNION ALL\n"
"SELECT s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,\n"
"       s1_norm_name,s1_norm_addr,s1_postal,s1_door,\n"
"       t_country,t_raw_name,t_raw_addr,t_norm_name,t_norm_addr,t_postal,t_door,\n"
"       jaccard_score,candidate_rank,0 as label\n"
"FROM hard_neg_v2;\n"
"\"\"\")\n"
"\n"
"train_v2_cnt = con.execute('SELECT count(*) FROM train_v2').fetchone()[0]\n"
"val_v2_cnt   = con.execute(\"SELECT count(*) FROM labeled_best WHERE split='val'\").fetchone()[0]\n"
"print(f'train_v2: {train_v2_cnt:,}  val_v2: {val_v2_cnt:,}')\n"
"\n"
"# ── Chunked feature extraction ─────────────────────────────────────────────\n"
"print(f'Extracting features v2 ({N_FEAT_V2} features)...')\n"
"t_feat2 = time.time()\n"
"COLS_V2 = ('s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,'\n"
"           's1_norm_name,s1_norm_addr,s1_postal,s1_door,'\n"
"           't_country,t_raw_name,t_raw_addr,t_norm_name,t_norm_addr,t_postal,t_door,'\n"
"           'jaccard_score,candidate_rank,label')\n"
"\n"
"X_train_v2 = _np2.empty((train_v2_cnt, N_FEAT_V2), dtype=_np2.float32)\n"
"y_train_v2 = _np2.empty(train_v2_cnt, dtype=_np2.int32)\n"
"offset = 0\n"
"n_tr_chunks = (train_v2_cnt + FEATURE_CHUNK_SIZE - 1) // FEATURE_CHUNK_SIZE\n"
"for ci in range(n_tr_chunks):\n"
"    chunk_df = con.execute(f'SELECT {COLS_V2} FROM train_v2 LIMIT {FEATURE_CHUNK_SIZE} OFFSET {ci*FEATURE_CHUNK_SIZE}').df()\n"
"    _fill_X_v2(chunk_df, X_train_v2, y_train_v2, offset, K_BEST, top_jac_map, max_pass_val)\n"
"    offset += len(chunk_df)\n"
"    del chunk_df; gc.collect()\n"
"    if (ci+1) % 5 == 0 or ci == n_tr_chunks-1:\n"
"        print(f'  train chunk {ci+1}/{n_tr_chunks}  rows={offset:,}')\n"
"\n"
"X_val_v2   = _np2.empty((val_v2_cnt, N_FEAT_V2), dtype=_np2.float32)\n"
"y_val_v2   = _np2.empty(val_v2_cnt, dtype=_np2.int32)\n"
"val_s1_ids_v2  = _np2.empty(val_v2_cnt, dtype=object)\n"
"val_tgt_ids_v2 = _np2.empty(val_v2_cnt, dtype=object)\n"
"offset = 0\n"
"n_vl_chunks = (val_v2_cnt + FEATURE_CHUNK_SIZE - 1) // FEATURE_CHUNK_SIZE\n"
"for ci in range(n_vl_chunks):\n"
"    chunk_df = con.execute(f\"SELECT {COLS_V2} FROM labeled_best WHERE split='val' LIMIT {FEATURE_CHUNK_SIZE} OFFSET {ci*FEATURE_CHUNK_SIZE}\").df()\n"
"    _fill_X_v2(chunk_df, X_val_v2, y_val_v2, offset, K_BEST, top_jac_map, max_pass_val)\n"
"    val_s1_ids_v2 [offset:offset+len(chunk_df)] = chunk_df['s1_id'].values\n"
"    val_tgt_ids_v2[offset:offset+len(chunk_df)] = chunk_df['target_id'].values\n"
"    offset += len(chunk_df)\n"
"    del chunk_df; gc.collect()\n"
"    if (ci+1) % 5 == 0 or ci == n_vl_chunks-1:\n"
"        print(f'  val chunk {ci+1}/{n_vl_chunks}  rows={offset:,}')\n"
"\n"
"print(f'Feature extraction v2 done in {time.time()-t_feat2:.1f}s')\n"
"print(f'  X_train_v2: {X_train_v2.shape}  X_val_v2: {X_val_v2.shape}')\n"
"nan_v2 = int(_np2.isnan(X_train_v2).sum())\n"
"inf_v2 = int(_np2.isinf(X_train_v2).sum())\n"
"print(f'  NaN: {nan_v2}  Inf: {inf_v2}')\n"
"if nan_v2 > 0 or inf_v2 > 0:\n"
"    raise ValueError('NaN/Inf in X_train_v2!')\n"
"print('  [PASS] Feature validation passed.')\n"
)

nb['cells'].append(code(src_22))

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
print(f'Cells: {len(nb["cells"])}  Part5 written.')
