"""Append strategies D (permutation), E (char n-gram), F (address) blocking cells."""
import json

NB = r'c:\Users\akash\OneDrive\Desktop\Amazon ML Challenge\notebooks\train_matching_model_colab.ipynb'

with open(NB, 'r', encoding='utf-8') as f:
    nb = json.load(f)

def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

# ── Strategy D: permutation passes ────────────────────────────────────────
src_d = (
"# ── Strategy D: 8-pass + 4 permutation passes, K=50 ─────────────────────\n"
"# Permutation passes: p2+p1, p1+p3, cmp4 prefix, p2+postal\n"
"print('Strategy D: 8-pass + permutation passes, K=50...')\n"
"t0 = time.time(); m0 = _mem_mb()\n"
"K_D = 50\n"
"con.execute(\"\"\"\n"
"CREATE OR REPLACE TABLE raw_cands_D AS\n"
"SELECT sub.entity_id as s1_id, sub.target_id, count(*) as pass_count\n"
"FROM (\n"
"    -- original 8 passes\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.p2=t.p2 WHERE length(s.p1)>=3 AND length(s.p2)>=3\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.postal=t.postal WHERE length(s.p1)>=3 AND s.postal!=''\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.door=t.door WHERE length(s.p1)>=3 AND s.door!=''\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.cmp5=t.cmp5 WHERE length(s.cmp5)>=5\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 WHERE length(s.p1)>=5\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.postal=t.postal AND s.door=t.door WHERE s.postal!='' AND length(s.door)>=2\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.door=t.door AND s.a1=t.a1 WHERE length(s.door)>=2 AND length(s.a1)>=4\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.door=t.door AND s.a2=t.a2 WHERE length(s.door)>=2 AND length(s.a2)>=4\n"
"    -- permutation pass 1: p2+p1 (word order swap)\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p2=t.p1 AND s.p1=t.p2 WHERE length(s.p1)>=3 AND length(s.p2)>=3\n"
"    -- permutation pass 2: p1+p3\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.p3=t.p3 WHERE length(s.p1)>=3 AND length(s.p3)>=3\n"
"    -- permutation pass 3: cmp4 prefix\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.cmp4=t.cmp4 WHERE length(s.cmp4)>=4\n"
"    -- permutation pass 4: p2+postal\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p2=t.p2 AND s.postal=t.postal WHERE length(s.p2)>=3 AND s.postal!=''\n"
") sub\n"
"GROUP BY sub.entity_id, sub.target_id;\n"
"\"\"\")\n"
"raw_d = con.execute('SELECT count(*) FROM raw_cands_D').fetchone()[0]\n"
"print(f'  Raw pairs D: {raw_d:,}')\n"
"\n"
"con.execute('CREATE OR REPLACE TABLE topk_D (s1_id VARCHAR, target_id VARCHAR, pass_count BIGINT,'\n"
"            ' split VARCHAR, s1_country VARCHAR,'\n"
"            ' s1_raw_name VARCHAR, s1_raw_addr VARCHAR,'\n"
"            ' s1_norm_name VARCHAR, s1_norm_addr VARCHAR,'\n"
"            ' s1_postal VARCHAR, s1_door VARCHAR,'\n"
"            ' t_country VARCHAR, t_raw_name VARCHAR, t_raw_addr VARCHAR,'\n"
"            ' t_norm_name VARCHAR, t_norm_addr VARCHAR,'\n"
"            ' t_postal VARCHAR, t_door VARCHAR,'\n"
"            ' jaccard_score DOUBLE, candidate_rank BIGINT);')\n"
"s1_ids_d = [r[0] for r in con.execute('SELECT DISTINCT s1_id FROM raw_cands_D ORDER BY s1_id').fetchall()]\n"
"n_chunks_d = (len(s1_ids_d) + RANK_CHUNK_SIZE - 1) // RANK_CHUNK_SIZE\n"
"for ci in range(n_chunks_d):\n"
"    chunk = s1_ids_d[ci*RANK_CHUNK_SIZE:(ci+1)*RANK_CHUNK_SIZE]\n"
"    con.register('_cids', pd.DataFrame({'s1_id': chunk}))\n"
"    con.execute(f\"\"\"\n"
"    INSERT INTO topk_D\n"
"    SELECT s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,\n"
"           s1_norm_name,s1_norm_addr,s1_postal,s1_door,t_country,t_raw_name,t_raw_addr,\n"
"           t_norm_name,t_norm_addr,t_postal,t_door,jaccard_score,candidate_rank\n"
"    FROM (\n"
"        SELECT c.s1_id,c.target_id,c.pass_count,s.split,s.country AS s1_country,\n"
"               s.raw_name AS s1_raw_name,s.raw_addr AS s1_raw_addr,\n"
"               s.norm_name AS s1_norm_name,s.norm_addr AS s1_norm_addr,\n"
"               s.postal AS s1_postal,s.door AS s1_door,\n"
"               t.country AS t_country,t.raw_name AS t_raw_name,t.raw_addr AS t_raw_addr,\n"
"               t.norm_name AS t_norm_name,t.norm_addr AS t_norm_addr,\n"
"               t.postal AS t_postal,t.door AS t_door,\n"
"               (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float/\n"
"                     nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0))+\n"
"                0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float/\n"
"                     nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0)))\n"
"               AS jaccard_score,\n"
"               row_number() OVER (PARTITION BY c.s1_id ORDER BY\n"
"                   (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float/\n"
"                         nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0))+\n"
"                    0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float/\n"
"                         nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0))) DESC,\n"
"                   c.pass_count DESC) AS candidate_rank\n"
"        FROM raw_cands_D c\n"
"        JOIN _cids x ON c.s1_id=x.s1_id\n"
"        JOIN s1_split s ON c.s1_id=s.entity_id\n"
"        JOIN target_pool t ON c.target_id=t.entity_id\n"
"    ) ranked WHERE candidate_rank <= {K_D};\n"
"    \"\"\")\n"
"tot,s1s,avg,p95 = _cand_stats(con,'topk_D')\n"
"r25 = _recall_at_k(con,'topk_D',25,val_gt)\n"
"r50 = _recall_at_k(con,'topk_D',50,val_gt)\n"
"blocking_results.append({\n"
"    'strategy':'D_8pass_perm_K50','K':50,\n"
"    'candidate_pairs':tot,'avg_cands':round(avg,1),'p95_cands':p95,\n"
"    'recall_at_25':round(r25,4),'recall_at_50':round(r50,4),'recall_at_100':round(r50,4),\n"
"    'runtime_s':round(time.time()-t0,1),'peak_mem_mb':round(_mem_mb()-m0,1)\n"
"})\n"
"print(f'  pairs={tot:,}  avg={avg:.1f}  p95={p95}  recall@25={r25:.4f}  recall@50={r50:.4f}')\n"
"gc.collect()\n"
)

nb['cells'].append(code(src_d))

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
print(f'Cells: {len(nb["cells"])}  Part4a written.')
