import json, os, sys

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

# ── SEC 6: S1 SPLIT + LEAKAGE CHECKS ──────────────────────────────────────────
NB["cells"].append(md(
    "### Section 6: S1 Entity Sampling & Train/Validation Split\n\n"
    "**Anti-Leakage Guarantee**: All candidate pairs for a given S1 entity stay entirely in train OR val.\n"
    "Explicit leakage checks are printed and will raise an error if any leakage is detected.\n"
))
NB["cells"].append(code(
    "TRAIN_S1_LIMIT = 150000\n"
    "VALIDATION_FRACTION = 0.20\n"
    "CHUNK_SIZE = 50000\n"
    "TOP_K = 25\n"
    "HARD_NEG_RATIO = 3.0\n\n"
    "print(f'Sampling {TRAIN_S1_LIMIT} S1 entities with SEED={SEED}...')\n"
    "sample_clause = f'USING SAMPLE {TRAIN_S1_LIMIT} (reservoir, {SEED})'\n\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE s1_sample AS\n"
    "SELECT entity_id, coalesce(country,'') as country,\n"
    "    business_name as raw_name, business_address as raw_addr,\n"
    "    norm_text(business_name) as norm_name,\n"
    "    clean_legal(business_name) as core_name,\n"
    "    clean_addr(business_address) as norm_addr,\n"
    "    get_token(clean_legal(business_name),1) as p1,\n"
    "    get_token(clean_legal(business_name),2) as p2,\n"
    "    get_token(clean_legal(business_name),3) as p3,\n"
    "    left(compact_name(business_name),4) as cmp4,\n"
    "    left(compact_name(business_name),5) as cmp5,\n"
    "    regexp_extract(clean_addr(business_address),'\\\\b(\\\\d{{3,}})\\\\b',1) as postal,\n"
    "    regexp_extract(clean_addr(business_address),'^(\\\\d+)',1) as door,\n"
    "    get_token(clean_addr(business_address),1) as a1,\n"
    "    get_token(clean_addr(business_address),2) as a2\n"
    "FROM read_csv_auto('{s1_path}', delim='\\t', header=true, quote='')\n"
    "{sample_clause};\n"
    "\"\"\")\n\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE s1_gt AS\n"
    "SELECT s.*, g.matched_entity_ids,\n"
    "    case when g.matched_entity_ids is null or trim(g.matched_entity_ids)='' then 0\n"
    "         else length(g.matched_entity_ids)-length(replace(g.matched_entity_ids,',',''))+1 end as match_count,\n"
    "    case when g.matched_entity_ids is null or trim(g.matched_entity_ids)='' then 1 else 0 end as is_singleton\n"
    "FROM s1_sample s\n"
    "LEFT JOIN read_csv_auto('{gt_path}', delim='\\t', header=true, quote='') g\n"
    "ON s.entity_id = g.source1_entity_id;\n"
    "\"\"\")\n\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE s1_split AS\n"
    "SELECT *,\n"
    "    case when row_number() over (partition by country,is_singleton order by hash(entity_id))\n"
    "              <= count(*) over (partition by country,is_singleton) * (1.0 - {VALIDATION_FRACTION})\n"
    "         then 'train' else 'val' end as split\n"
    "FROM s1_gt;\n"
    "\"\"\")\n\n"
    "dist_df = con.execute(\"\"\"\n"
    "SELECT split, country, count(*) as s1_count,\n"
    "       sum(is_singleton) as singleton_count,\n"
    "       round(sum(is_singleton)::float/count(*)*100,2) as singleton_pct,\n"
    "       sum(match_count) as total_true_matches,\n"
    "       round(avg(match_count),2) as avg_matches_per_s1\n"
    "FROM s1_split GROUP BY split,country ORDER BY split,country\n"
    "\"\"\").df()\n"
    "print('\\nTrain / Validation S1 Entity Distributions:')\n"
    "display(dist_df)\n\n"
    "# ── EXPLICIT LEAKAGE CHECKS ────────────────────────────────────────────────\n"
    "print('\\n' + '='*60)\n"
    "print('LEAKAGE CHECKS')\n"
    "print('='*60)\n\n"
    "# Check 1: no S1 entity appears in both splits\n"
    "overlap = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM\n"
    "        (SELECT entity_id FROM s1_split WHERE split='train') t\n"
    "        JOIN (SELECT entity_id FROM s1_split WHERE split='val') v\n"
    "        ON t.entity_id = v.entity_id\n"
    "\"\"\").fetchone()[0]\n"
    "print(f'S1 entities in BOTH train and val: {overlap}')\n"
    "if overlap > 0:\n"
    "    raise AssertionError(f'LEAKAGE DETECTED: {overlap} S1 entities appear in both splits!')\n"
    "print('  [PASS] No S1 entity appears in both splits.')\n\n"
    "# Check 2: every s1_split row has exactly one split value\n"
    "multi_split = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM (\n"
    "        SELECT entity_id, count(distinct split) as n\n"
    "        FROM s1_split GROUP BY entity_id HAVING n > 1\n"
    "    )\n"
    "\"\"\").fetchone()[0]\n"
    "print(f'S1 entities with multiple split assignments: {multi_split}')\n"
    "if multi_split > 0:\n"
    "    raise AssertionError(f'LEAKAGE DETECTED: {multi_split} S1 entities have multiple split values!')\n"
    "print('  [PASS] Every S1 entity has exactly one split assignment.')\n\n"
    "# Check 3: split counts sum to total\n"
    "total_s1 = con.execute('SELECT count(*) FROM s1_split').fetchone()[0]\n"
    "train_s1 = con.execute(\"SELECT count(*) FROM s1_split WHERE split='train'\").fetchone()[0]\n"
    "val_s1   = con.execute(\"SELECT count(*) FROM s1_split WHERE split='val'\").fetchone()[0]\n"
    "print(f'Total S1: {total_s1:,}  Train: {train_s1:,}  Val: {val_s1:,}  Sum: {train_s1+val_s1:,}')\n"
    "if train_s1 + val_s1 != total_s1:\n"
    "    raise AssertionError('LEAKAGE DETECTED: split counts do not sum to total!')\n"
    "actual_val_frac = val_s1 / total_s1\n"
    "print(f'  [PASS] Val fraction: {actual_val_frac:.3f} (target {VALIDATION_FRACTION})')\n"
    "print('All leakage checks passed.')\n"
))

# ── SEC 7: TARGET POOL WITH EXPLICIT REPORTING ─────────────────────────────────
NB["cells"].append(md(
    "### Section 7: Final 8-Pass Blocking & Candidate Generation\n\n"
    "**Development Experiment**: true targets + random S2/S3 distractors (150k each).\n"
    "Target pool composition is explicitly reported below.\n"
))
NB["cells"].append(code(
    "print('Building Target Pool (true targets + random distractors)...')\n"
    "t0_pool = time.time()\n\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE true_target_ids AS\n"
    "SELECT DISTINCT unnest(string_split(matched_entity_ids,',')) as target_id\n"
    "FROM s1_gt WHERE matched_entity_ids is not null and trim(matched_entity_ids)!='';\n"
    "\"\"\")\n\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE target_pool AS\n"
    "SELECT entity_id, coalesce(country,'') as country,\n"
    "    business_name as raw_name, business_address as raw_addr,\n"
    "    norm_text(business_name) as norm_name,\n"
    "    clean_legal(business_name) as core_name,\n"
    "    clean_addr(business_address) as norm_addr,\n"
    "    get_token(clean_legal(business_name),1) as p1,\n"
    "    get_token(clean_legal(business_name),2) as p2,\n"
    "    get_token(clean_legal(business_name),3) as p3,\n"
    "    left(compact_name(business_name),4) as cmp4,\n"
    "    left(compact_name(business_name),5) as cmp5,\n"
    "    regexp_extract(clean_addr(business_address),'\\\\b(\\\\d{{3,}})\\\\b',1) as postal,\n"
    "    regexp_extract(clean_addr(business_address),'^(\\\\d+)',1) as door,\n"
    "    get_token(clean_addr(business_address),1) as a1,\n"
    "    get_token(clean_addr(business_address),2) as a2\n"
    "FROM (\n"
    "    SELECT * FROM read_csv_auto('{s2_path}', delim='\\t', header=true, quote='')\n"
    "    WHERE entity_id IN (SELECT target_id FROM true_target_ids)\n"
    "    UNION ALL\n"
    "    SELECT * FROM read_csv_auto('{s3_path}', delim='\\t', header=true, quote='')\n"
    "    WHERE entity_id IN (SELECT target_id FROM true_target_ids)\n"
    "    UNION ALL\n"
    "    (SELECT * FROM read_csv_auto('{s2_path}', delim='\\t', header=true, quote='') USING SAMPLE 150000 (reservoir, {SEED}))\n"
    "    UNION ALL\n"
    "    (SELECT * FROM read_csv_auto('{s3_path}', delim='\\t', header=true, quote='') USING SAMPLE 150000 (reservoir, {SEED}))\n"
    ");\n"
    "\"\"\")\n\n"
    "# ── TARGET POOL COMPOSITION REPORT ────────────────────────────────────────\n"
    "true_tgt_cnt = con.execute('SELECT count(*) FROM true_target_ids').fetchone()[0]\n"
    "total_pool   = con.execute('SELECT count(*) FROM target_pool').fetchone()[0]\n"
    "# true targets that landed in pool (from s2 or s3)\n"
    "true_in_pool = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM target_pool\n"
    "    WHERE entity_id IN (SELECT target_id FROM true_target_ids)\n"
    "\"\"\").fetchone()[0]\n"
    "rand_distractor_cnt = total_pool - true_in_pool\n"
    "pct_true = true_in_pool / total_pool * 100 if total_pool > 0 else 0\n\n"
    "print('\\n' + '='*60)\n"
    "print('TARGET POOL COMPOSITION  [DEVELOPMENT EXPERIMENT]')\n"
    "print('='*60)\n"
    "print(f'  True target IDs (unique):          {true_tgt_cnt:>10,}')\n"
    "print(f'  True target records in pool:       {true_in_pool:>10,}')\n"
    "print(f'  Random S2+S3 distractor records:   {rand_distractor_cnt:>10,}')\n"
    "print(f'  Total target pool records:         {total_pool:>10,}')\n"
    "print(f'  True-target % of pool:             {pct_true:>9.2f}%')\n"
    "print('  NOTE: This is a dev experiment. Full-scale training uses the')\n"
    "print('        complete S2+S3 corpus without random sampling.')\n"
    "print(f'  Built in {time.time()-t0_pool:.2f}s')\n\n"
    "# ── 8-PASS BLOCKING ───────────────────────────────────────────────────────\n"
    "print('\\nExecuting 8-pass blocking...')\n"
    "t_block = time.time()\n\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE raw_candidate_pairs AS\n"
    "SELECT sub.entity_id as s1_id, sub.target_id, count(*) as pass_count\n"
    "FROM (\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.p2=t.p2 WHERE length(s.p1)>=3 AND length(s.p2)>=3\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.postal=t.postal WHERE length(s.p1)>=3 AND s.postal!=''\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.door=t.door WHERE length(s.p1)>=3 AND s.door!=''\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.cmp5=t.cmp5 WHERE length(s.cmp5)>=5\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 WHERE length(s.p1)>=5\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.postal=t.postal AND s.door=t.door WHERE s.postal!='' AND length(s.door)>=2\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.door=t.door AND s.a1=t.a1 WHERE length(s.door)>=2 AND length(s.a1)>=4\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.door=t.door AND s.a2=t.a2 WHERE length(s.door)>=2 AND length(s.a2)>=4\n"
    ") sub\n"
    "GROUP BY sub.entity_id, sub.target_id;\n"
    "\"\"\")\n\n"
    "raw_pairs = con.execute('SELECT count(*) FROM raw_candidate_pairs').fetchone()[0]\n"
    "print(f'Generated {raw_pairs:,} distinct raw candidate pairs in {time.time()-t_block:.2f}s.')\n\n"
    "print(f'Ranking candidates and selecting top K={TOP_K} per S1 entity...')\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE ranked_candidates AS\n"
    "WITH pair_scored AS (\n"
    "    SELECT c.s1_id, c.target_id, c.pass_count,\n"
    "        s.split, s.country as s1_country,\n"
    "        s.raw_name as s1_raw_name, s.raw_addr as s1_raw_addr,\n"
    "        s.norm_name as s1_norm_name, s.norm_addr as s1_norm_addr,\n"
    "        s.postal as s1_postal, s.door as s1_door,\n"
    "        t.country as t_country,\n"
    "        t.raw_name as t_raw_name, t.raw_addr as t_raw_addr,\n"
    "        t.norm_name as t_norm_name, t.norm_addr as t_norm_addr,\n"
    "        t.postal as t_postal, t.door as t_door,\n"
    "        (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float /\n"
    "              nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0)) +\n"
    "         0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float /\n"
    "              nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0))) as jaccard_score\n"
    "    FROM raw_candidate_pairs c\n"
    "    JOIN s1_split s ON c.s1_id=s.entity_id\n"
    "    JOIN target_pool t ON c.target_id=t.entity_id\n"
    ")\n"
    "SELECT *,\n"
    "    row_number() over (partition by s1_id order by coalesce(jaccard_score,0) desc, pass_count desc) as candidate_rank\n"
    "FROM pair_scored;\n\n"
    "CREATE OR REPLACE TABLE topk_candidates AS\n"
    "SELECT * FROM ranked_candidates WHERE candidate_rank <= {TOP_K};\n"
    "\"\"\")\n\n"
    "topk_cnt = con.execute('SELECT count(*) FROM topk_candidates').fetchone()[0]\n"
    "per_s1 = [r[0] for r in con.execute('SELECT count(*) FROM topk_candidates GROUP BY s1_id').fetchall()]\n"
    "per_s1 = [x for x in per_s1 if x > 0]\n"
    "print(f'\\nCandidate Generation Results:')\n"
    "print(f'  Total Retained Pairs: {topk_cnt:,} across {len(per_s1):,} S1 entities')\n"
    "print(f'  Avg Candidates/S1:    {sum(per_s1)/len(per_s1):.1f}')\n"
    "print(f'  Median:               {sorted(per_s1)[len(per_s1)//2]}')\n"
    "print(f'  Maximum:              {max(per_s1)}')\n"
))

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print(f'Sections 6-7 appended to {nb_path}')
