import json, os, re

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

# ── LOCATE CELLS BY SECTION ────────────────────────────────────────────────────
# Find indices
sec7_md_idx   = None  # markdown for Section 7
sec7_code_idx = None  # code cell for Section 7 (target pool + blocking)
sec18_md_idx  = None  # markdown for Section 18

for i, cell in enumerate(NB['cells']):
    src = cell['source'] if isinstance(cell['source'], str) else ''.join(cell['source'])
    if cell['cell_type'] == 'markdown' and 'Section 7' in src and '8-Pass Blocking' in src:
        sec7_md_idx = i
    if cell['cell_type'] == 'code' and 'true_target_ids' in src and 'target_pool' in src and 'UNION ALL' in src:
        sec7_code_idx = i
    if cell['cell_type'] == 'markdown' and 'Section 18' in src and 'Final Experiment Summary' in src:
        sec18_md_idx = i

print(f'sec7_md_idx={sec7_md_idx}  sec7_code_idx={sec7_code_idx}  sec18_md_idx={sec18_md_idx}')
assert sec7_md_idx is not None,   'Could not find Section 7 markdown cell'
assert sec7_code_idx is not None, 'Could not find Section 7 code cell'
assert sec18_md_idx is not None,  'Could not find Section 18 markdown cell'

# ── CORRECTION 1 & 2: Section 7 markdown — add validation scope note ──────────
NB['cells'][sec7_md_idx]['source'] = (
    "### Section 7: Final 8-Pass Blocking & Candidate Generation\n\n"
    "**Development Experiment**: true targets + random S2/S3 distractors (150k each).\n"
    "Target pool is deduplicated to one unique record per entity_id before blocking.\n"
    "Target pool composition is explicitly reported below.\n\n"
    "> **Validation Scope**: This model validation measures matcher performance "
    "**conditional on the true target being present in the candidate-generation pool**. "
    "End-to-end blocking recall is evaluated separately by `blocking_experiment.py`. "
    "The F0.5 reported here is **not** the final end-to-end competition score.\n"
)

# ── CORRECTION 1: Section 7 code cell — add dedup + duplicate check ───────────
NB['cells'][sec7_code_idx]['source'] = (
    "print('Building Target Pool (true targets + random distractors)...')\n"
    "t0_pool = time.time()\n"
    "\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE true_target_ids AS\n"
    "SELECT DISTINCT unnest(string_split(matched_entity_ids,',')) as target_id\n"
    "FROM s1_gt WHERE matched_entity_ids is not null and trim(matched_entity_ids)!='';\n"
    "\"\"\")\n"
    "\n"
    "# Build raw pool with UNION ALL (may contain duplicate entity_ids)\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE target_pool_raw AS\n"
    "SELECT entity_id, coalesce(country,'') as country,\n"
    "    business_name as raw_name, business_address as raw_addr,\n"
    "    norm_text(business_name) as norm_name,\n"
    "    clean_legal(business_name) as core_name,\n"
    "    clean_addr(business_address) as norm_addr,\n"
    "    get_token(clean_legal(business_name),1) as p1,\n"
    "    get_token(clean_legal(business_name),2) as p2,\n"
    "    get_token(clean_legal(business_name),3) as p3,\n"
    "    left(compact_name(business_name),4) as cmp4,\n"
    "    left(compact_name(business_name),5) as cmp5,\n"
    "    regexp_extract(clean_addr(business_address),'\\\\b(\\\\d{{3,}})\\\\b',1) as postal,\n"
    "    regexp_extract(clean_addr(business_address),'^(\\\\d+)',1) as door,\n"
    "    get_token(clean_addr(business_address),1) as a1,\n"
    "    get_token(clean_addr(business_address),2) as a2\n"
    "FROM (\n"
    "    SELECT * FROM read_csv_auto('{s2_path}', delim='\\t', header=true, quote='')\n"
    "    WHERE entity_id IN (SELECT target_id FROM true_target_ids)\n"
    "    UNION ALL\n"
    "    SELECT * FROM read_csv_auto('{s3_path}', delim='\\t', header=true, quote='')\n"
    "    WHERE entity_id IN (SELECT target_id FROM true_target_ids)\n"
    "    UNION ALL\n"
    "    (SELECT * FROM read_csv_auto('{s2_path}', delim='\\t', header=true, quote='') USING SAMPLE 150000 (reservoir, {SEED}))\n"
    "    UNION ALL\n"
    "    (SELECT * FROM read_csv_auto('{s3_path}', delim='\\t', header=true, quote='') USING SAMPLE 150000 (reservoir, {SEED}))\n"
    ");\n"
    "\"\"\")\n"
    "\n"
    "raw_pool_cnt = con.execute('SELECT count(*) FROM target_pool_raw').fetchone()[0]\n"
    "dup_cnt_before = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM (\n"
    "        SELECT entity_id FROM target_pool_raw\n"
    "        GROUP BY entity_id HAVING count(*) > 1\n"
    "    )\n"
    "\"\"\").fetchone()[0]\n"
    "print(f'Raw pool (before dedup): {raw_pool_cnt:,} records, {dup_cnt_before:,} entity_ids with duplicates')\n"
    "\n"
    "# Deduplicate: keep one record per entity_id, preferring true-target rows\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE target_pool AS\n"
    "SELECT entity_id, country, raw_name, raw_addr, norm_name, core_name, norm_addr,\n"
    "       p1, p2, p3, cmp4, cmp5, postal, door, a1, a2\n"
    "FROM (\n"
    "    SELECT *,\n"
    "        row_number() over (\n"
    "            partition by entity_id\n"
    "            order by entity_id  -- deterministic tie-break\n"
    "        ) as rn\n"
    "    FROM target_pool_raw\n"
    ")\n"
    "WHERE rn = 1;\n"
    "\"\"\")\n"
    "\n"
    "# ── DUPLICATE CHECK — FAIL LOUDLY IF ANY REMAIN ───────────────────────────\n"
    "dup_cnt_after = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM (\n"
    "        SELECT entity_id, count(*) as n\n"
    "        FROM target_pool\n"
    "        GROUP BY entity_id HAVING n > 1\n"
    "    )\n"
    "\"\"\").fetchone()[0]\n"
    "if dup_cnt_after > 0:\n"
    "    raise AssertionError(f'DEDUP FAILED: {dup_cnt_after} entity_ids still have duplicate records in target_pool!')\n"
    "\n"
    "# ── TARGET POOL COMPOSITION REPORT ────────────────────────────────────────\n"
    "true_tgt_cnt = con.execute('SELECT count(*) FROM true_target_ids').fetchone()[0]\n"
    "total_pool   = con.execute('SELECT count(*) FROM target_pool').fetchone()[0]\n"
    "true_in_pool = con.execute(\"\"\"\n"
    "    SELECT count(*) FROM target_pool\n"
    "    WHERE entity_id IN (SELECT target_id FROM true_target_ids)\n"
    "\"\"\").fetchone()[0]\n"
    "rand_distractor_cnt = total_pool - true_in_pool\n"
    "pct_true = true_in_pool / total_pool * 100 if total_pool > 0 else 0\n"
    "\n"
    "print('\\n' + '='*60)\n"
    "print('TARGET POOL COMPOSITION  [DEVELOPMENT EXPERIMENT]')\n"
    "print('='*60)\n"
    "print(f'  Duplicate entity_ids before dedup:   {dup_cnt_before:>10,}')\n"
    "print(f'  Duplicate entity_ids after dedup:    {dup_cnt_after:>10,}  [PASS]')\n"
    "print(f'  True target IDs (unique):            {true_tgt_cnt:>10,}')\n"
    "print(f'  True target records in pool:         {true_in_pool:>10,}')\n"
    "print(f'  Random S2+S3 distractor records:     {rand_distractor_cnt:>10,}')\n"
    "print(f'  Total unique target pool records:    {total_pool:>10,}')\n"
    "print(f'  True-target % of pool:               {pct_true:>9.2f}%')\n"
    "print('  NOTE: Dev experiment — full-scale training uses complete S2+S3 corpus.')\n"
    "print(f'  Built in {time.time()-t0_pool:.2f}s')\n"
    "\n"
    "# ── 8-PASS BLOCKING ───────────────────────────────────────────────────────\n"
    "print('\\nExecuting 8-pass blocking...')\n"
    "t_block = time.time()\n"
    "\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE raw_candidate_pairs AS\n"
    "SELECT sub.entity_id as s1_id, sub.target_id, count(*) as pass_count\n"
    "FROM (\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.p2=t.p2 WHERE length(s.p1)>=3 AND length(s.p2)>=3\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.postal=t.postal WHERE length(s.p1)>=3 AND s.postal!=''\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 AND s.door=t.door WHERE length(s.p1)>=3 AND s.door!=''\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.cmp5=t.cmp5 WHERE length(s.cmp5)>=5\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.p1=t.p1 WHERE length(s.p1)>=5\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.postal=t.postal AND s.door=t.door WHERE s.postal!='' AND length(s.door)>=2\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.door=t.door AND s.a1=t.a1 WHERE length(s.door)>=2 AND length(s.a1)>=4\n"
    "    UNION ALL\n"
    "    SELECT s.entity_id,t.entity_id as target_id FROM s1_split s JOIN target_pool t ON s.country=t.country AND s.door=t.door AND s.a2=t.a2 WHERE length(s.door)>=2 AND length(s.a2)>=4\n"
    ") sub\n"
    "GROUP BY sub.entity_id, sub.target_id;\n"
    "\"\"\")\n"
    "\n"
    "raw_pairs = con.execute('SELECT count(*) FROM raw_candidate_pairs').fetchone()[0]\n"
    "print(f'Generated {raw_pairs:,} distinct raw candidate pairs in {time.time()-t_block:.2f}s.')\n"
    "\n"
    "print(f'Ranking candidates and selecting top K={TOP_K} per S1 entity...')\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE ranked_candidates AS\n"
    "WITH pair_scored AS (\n"
    "    SELECT c.s1_id, c.target_id, c.pass_count,\n"
    "        s.split, s.country as s1_country,\n"
    "        s.raw_name as s1_raw_name, s.raw_addr as s1_raw_addr,\n"
    "        s.norm_name as s1_norm_name, s.norm_addr as s1_norm_addr,\n"
    "        s.postal as s1_postal, s.door as s1_door,\n"
    "        t.country as t_country,\n"
    "        t.raw_name as t_raw_name, t.raw_addr as t_raw_addr,\n"
    "        t.norm_name as t_norm_name, t.norm_addr as t_norm_addr,\n"
    "        t.postal as t_postal, t.door as t_door,\n"
    "        (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float /\n"
    "              nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0)) +\n"
    "         0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float /\n"
    "              nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0))) as jaccard_score\n"
    "    FROM raw_candidate_pairs c\n"
    "    JOIN s1_split s ON c.s1_id=s.entity_id\n"
    "    JOIN target_pool t ON c.target_id=t.entity_id\n"
    ")\n"
    "SELECT *,\n"
    "    row_number() over (partition by s1_id order by coalesce(jaccard_score,0) desc, pass_count desc) as candidate_rank\n"
    "FROM pair_scored;\n"
    "\n"
    "CREATE OR REPLACE TABLE topk_candidates AS\n"
    "SELECT * FROM ranked_candidates WHERE candidate_rank <= {TOP_K};\n"
    "\"\"\")\n"
    "\n"
    "topk_cnt = con.execute('SELECT count(*) FROM topk_candidates').fetchone()[0]\n"
    "per_s1 = [r[0] for r in con.execute('SELECT count(*) FROM topk_candidates GROUP BY s1_id').fetchall()]\n"
    "per_s1 = [x for x in per_s1 if x > 0]\n"
    "print(f'\\nCandidate Generation Results:')\n"
    "print(f'  Total Retained Pairs: {topk_cnt:,} across {len(per_s1):,} S1 entities')\n"
    "print(f'  Avg Candidates/S1:    {sum(per_s1)/len(per_s1):.1f}')\n"
    "print(f'  Median:               {sorted(per_s1)[len(per_s1)//2]}')\n"
    "print(f'  Maximum:              {max(per_s1)}')\n"
)

# ── CORRECTION 3: Section 18 markdown — add EVALUATION TYPE field ─────────────
NB['cells'][sec18_md_idx]['source'] = (
    "### Section 18: Final Experiment Summary\n\n"
    "**This was a DEVELOPMENT EXPERIMENT** (150k S1 entities, random distractors).\n\n"
    "1. **Blocking**: Finalized 8-pass architecture, K=25, zero OOM overhead.\n"
    "2. **Hard Negatives**: 6-category deliberate sampling at HARD_NEG_RATIO=3.0.\n"
    "3. **Target Pool**: Deduplicated (one unique record per entity_id). "
    "Duplicate count before/after reported. True-target %, S2/S3 distractor counts reported.\n"
    "4. **Leakage**: Explicit checks — no S1 in both splits, no cross-split candidate pairs.\n"
    "5. **F0.5**: Unit-tested implementation, all val S1s evaluated including singletons.\n"
    "6. **Feature Validation**: NaN/inf, min/max/mean, constant, redundant features checked.\n"
    "7. **Models**: LR vs XGBoost on identical splits. Threshold selected on val only.\n"
    "8. **Reproducibility**: SEED=42, TRAIN_S1_LIMIT=150000, VALIDATION_FRACTION=0.20, TOP_K=25.\n\n"
    "---\n\n"
    "```\n"
    "EVALUATION TYPE:\n"
    "  Conditional matcher validation — not end-to-end test evaluation\n\n"
    "  The F0.5 scores above measure how well the matcher ranks and selects\n"
    "  candidates given that the true target was already present in the pool.\n"
    "  They do NOT reflect end-to-end competition performance, which also\n"
    "  depends on blocking recall over the full S2+S3 corpus.\n"
    "  End-to-end blocking recall is evaluated separately by blocking_experiment.py.\n"
    "```\n"
)

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print('3 corrections applied and saved.')
