import json, os

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

NB["cells"].append(md(
    "### Section 8 & 9: Positive / Negative Labels & Deliberate Hard-Negative Sampling\n\n"
    "Negatives are sampled across **6 deliberate categories**:\n"
    "1. `high_name_low_addr` — name sim >= 80, addr sim < 40\n"
    "2. `high_addr_low_name` — addr sim >= 75, name sim < 40\n"
    "3. `high_name_conflict_door` — name sim >= 70, door numbers differ\n"
    "4. `high_addr_diff_name` — addr sim >= 70, name sim < 60\n"
    "5. `generic_name_collision` — very short/common name (<=5 chars stripped)\n"
    "6. `remaining_difficult` — high jaccard but uncategorised\n\n"
    "Budget is split proportionally across categories. Total = positives x HARD_NEG_RATIO.\n"
))

NB["cells"].append(code(
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE labeled_topk AS\n"
    "SELECT c.*,\n"
    "    case when g.target_id is not null then 1 else 0 end as label\n"
    "FROM topk_candidates c\n"
    "LEFT JOIN (\n"
    "    SELECT entity_id as s1_id, unnest(string_split(matched_entity_ids,',')) as target_id\n"
    "    FROM s1_gt WHERE matched_entity_ids is not null\n"
    ") g ON c.s1_id=g.s1_id AND c.target_id=g.target_id;\n"
    "\"\"\")\n"
    "\n"
    "label_dist = con.execute(\"\"\"\n"
    "    SELECT split, label, count(*) as pair_count\n"
    "    FROM labeled_topk GROUP BY split,label ORDER BY split,label\n"
    "\"\"\").df()\n"
    "print('Raw Candidate Label Distribution:')\n"
    "display(label_dist)\n"
    "\n"
    "train_pos_cnt = con.execute(\"SELECT count(*) FROM labeled_topk WHERE split='train' AND label=1\").fetchone()[0]\n"
    "max_train_negs = int(train_pos_cnt * HARD_NEG_RATIO)\n"
    "print(f'Positives (train): {train_pos_cnt:,}  Target negatives: {max_train_negs:,}  Ratio: {HARD_NEG_RATIO}')\n"
    "\n"
    "from rapidfuzz import fuzz as _fuzz\n"
    "\n"
    "df_neg_pool = con.execute(\"\"\"\n"
    "    SELECT s1_id, target_id, pass_count, split, s1_country, t_country,\n"
    "           s1_raw_name, t_raw_name, s1_raw_addr, t_raw_addr,\n"
    "           s1_norm_name, t_norm_name, s1_norm_addr, t_norm_addr,\n"
    "           s1_postal, t_postal, s1_door, t_door,\n"
    "           coalesce(jaccard_score,0) as jaccard_score, candidate_rank\n"
    "    FROM labeled_topk WHERE split='train' AND label=0\n"
    "\"\"\").df()\n"
    "print(f'Train negative pool: {len(df_neg_pool):,}')\n"
    "\n"
    "s1n = df_neg_pool['s1_norm_name'].fillna('').values\n"
    "tn  = df_neg_pool['t_norm_name'].fillna('').values\n"
    "s1a = df_neg_pool['s1_norm_addr'].fillna('').values\n"
    "ta  = df_neg_pool['t_norm_addr'].fillna('').values\n"
    "s1d = df_neg_pool['s1_door'].fillna('').values\n"
    "td  = df_neg_pool['t_door'].fillna('').values\n"
    "\n"
    "name_sim = [_fuzz.token_sort_ratio(a,b) for a,b in zip(s1n,tn)]\n"
    "addr_sim = [_fuzz.token_sort_ratio(a,b) for a,b in zip(s1a,ta)]\n"
    "\n"
    "cats = []\n"
    "for i in range(len(df_neg_pool)):\n"
    "    ns, as_ = name_sim[i], addr_sim[i]\n"
    "    if ns >= 80 and as_ < 40:\n"
    "        cats.append('high_name_low_addr')\n"
    "    elif as_ >= 75 and ns < 40:\n"
    "        cats.append('high_addr_low_name')\n"
    "    elif ns >= 70 and s1d[i] and td[i] and s1d[i] != td[i]:\n"
    "        cats.append('high_name_conflict_door')\n"
    "    elif as_ >= 70 and ns < 60:\n"
    "        cats.append('high_addr_diff_name')\n"
    "    elif len(s1n[i].replace(' ','')) <= 5:\n"
    "        cats.append('generic_name_collision')\n"
    "    else:\n"
    "        cats.append('remaining_difficult')\n"
    "\n"
    "df_neg_pool['hard_neg_category'] = cats\n"
    "cat_counts = df_neg_pool['hard_neg_category'].value_counts()\n"
    "print('\\nHard-Negative Category Counts (full pool):')\n"
    "for cat, cnt in cat_counts.items():\n"
    "    print(f'  {cat:<30}: {cnt:>8,}')\n"
    "\n"
    "total_pool_neg = len(df_neg_pool)\n"
    "sampled_parts = []\n"
    "remaining_budget = max_train_negs\n"
    "cat_order = cat_counts.index.tolist()\n"
    "for i, cat in enumerate(cat_order):\n"
    "    cat_df = df_neg_pool[df_neg_pool['hard_neg_category'] == cat]\n"
    "    share = int(max_train_negs * len(cat_df) / total_pool_neg)\n"
    "    if i == len(cat_order) - 1:\n"
    "        share = remaining_budget\n"
    "    share = min(share, len(cat_df), remaining_budget)\n"
    "    if share > 0:\n"
    "        sampled_parts.append(cat_df.sample(n=share, random_state=SEED))\n"
    "        remaining_budget -= share\n"
    "\n"
    "df_hard_negs = pd.concat(sampled_parts, ignore_index=True)\n"
    "df_hard_negs['label'] = 0\n"
    "\n"
    "print('\\nSampled Hard-Negative Counts by Category:')\n"
    "for cat, cnt in df_hard_negs['hard_neg_category'].value_counts().items():\n"
    "    print(f'  {cat:<30}: {cnt:>8,}')\n"
    "print(f'  {\"TOTAL\":<30}: {len(df_hard_negs):>8,}')\n"
    "\n"
    "con.register('df_hard_negs_view', df_hard_negs)\n"
    "con.execute(\"\"\"\n"
    "CREATE OR REPLACE TABLE train_pairs_selected AS\n"
    "SELECT s1_id, target_id, pass_count, split, s1_country, s1_raw_name, s1_raw_addr,\n"
    "       s1_norm_name, s1_norm_addr, s1_postal, s1_door,\n"
    "       t_country, t_raw_name, t_raw_addr, t_norm_name, t_norm_addr, t_postal, t_door,\n"
    "       jaccard_score, candidate_rank, 1 as label\n"
    "FROM labeled_topk WHERE split='train' AND label=1\n"
    "UNION ALL\n"
    "SELECT s1_id, target_id, pass_count, split, s1_country, s1_raw_name, s1_raw_addr,\n"
    "       s1_norm_name, s1_norm_addr, s1_postal, s1_door,\n"
    "       t_country, t_raw_name, t_raw_addr, t_norm_name, t_norm_addr, t_postal, t_door,\n"
    "       jaccard_score, candidate_rank, 0 as label\n"
    "FROM df_hard_negs_view;\n"
    "\"\"\")\n"
    "\n"
    "final_train_cnt = con.execute('SELECT count(*) FROM train_pairs_selected').fetchone()[0]\n"
    "final_neg_cnt   = final_train_cnt - train_pos_cnt\n"
    "print(f'\\nBalanced Training Set:')\n"
    "print(f'  Positive Pairs:  {train_pos_cnt:,}')\n"
    "print(f'  Hard Negatives:  {final_neg_cnt:,}')\n"
    "print(f'  Ratio (Neg:Pos): {final_neg_cnt/train_pos_cnt:.2f}:1')\n"
    "print(f'  Total Pairs:     {final_train_cnt:,}')\n"
))

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print('Sections 8-9 appended.')
