import json, os

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

NB["cells"].append(md(
    "### Section 10: Feature Engineering (24 Features) + Feature Validation\n\n"
    "24 similarity features computed with RapidFuzz on top-K pairs only.\n"
    "Before model training, feature validation checks:\n"
    "- No NaN / inf values\n"
    "- Feature min / max / mean\n"
    "- Constant features (zero variance)\n"
    "- Highly duplicated / redundant features (correlation > 0.98)\n"
    "- Feature name alignment with X_train columns\n"
))

NB["cells"].append(code(
    "FEATURE_NAMES = [\n"
    "    'name_exact_raw','name_exact_norm','name_token_sort_ratio','name_token_set_ratio',\n"
    "    'name_jaro_winkler','name_levenshtein_ratio','name_char_sim','name_substring_containment',\n"
    "    'addr_exact_norm','addr_token_sort_ratio','addr_token_set_ratio','addr_token_jaccard',\n"
    "    'addr_char_sim','addr_num_overlap','addr_postal_match',\n"
    "    'country_agreement','s1_name_missing','t_name_missing','s1_addr_missing','t_addr_missing',\n"
    "    'candidate_rank','blocking_pass_count','name_x_addr','name_diff_addr'\n"
    "]\n"
    "\n"
    "from rapidfuzz import fuzz, distance\n"
    "\n"
    "def compute_pair_features(s1_raw,s1_norm,s1_addr,s1_postal,s1_door,\n"
    "                           t_raw,t_norm,t_addr,t_postal,t_door,\n"
    "                           s1_country,t_country,rank,pass_count):\n"
    "    exact_raw  = 1.0 if s1_raw and s1_raw==t_raw else 0.0\n"
    "    exact_norm = 1.0 if s1_norm and s1_norm==t_norm else 0.0\n"
    "    name_sort  = fuzz.token_sort_ratio(s1_norm,t_norm)/100.0\n"
    "    name_set   = fuzz.token_set_ratio(s1_norm,t_norm)/100.0\n"
    "    jw         = distance.JaroWinkler.similarity(s1_norm,t_norm)\n"
    "    lev        = distance.Levenshtein.normalized_similarity(s1_norm,t_norm)\n"
    "    name_char  = fuzz.ratio(s1_norm,t_norm)/100.0\n"
    "    name_sub   = 1.0 if (s1_norm and t_norm and (s1_norm in t_norm or t_norm in s1_norm)) else 0.0\n"
    "    addr_exact = 1.0 if s1_addr and s1_addr==t_addr else 0.0\n"
    "    addr_sort  = fuzz.token_sort_ratio(s1_addr,t_addr)/100.0\n"
    "    addr_set   = fuzz.token_set_ratio(s1_addr,t_addr)/100.0\n"
    "    s1_at = set(s1_addr.split()) if s1_addr else set()\n"
    "    t_at  = set(t_addr.split())  if t_addr  else set()\n"
    "    addr_jac   = len(s1_at&t_at)/len(s1_at|t_at) if (s1_at or t_at) else 0.0\n"
    "    addr_char  = fuzz.ratio(s1_addr,t_addr)/100.0\n"
    "    s1_nums = {w for w in s1_at if w.isdigit()}\n"
    "    t_nums  = {w for w in t_at  if w.isdigit()}\n"
    "    if s1_nums and t_nums:   num_ov = len(s1_nums&t_nums)/len(s1_nums|t_nums)\n"
    "    elif not s1_nums and not t_nums: num_ov = 0.5\n"
    "    else:                    num_ov = 0.0\n"
    "    postal_m   = 1.0 if s1_postal and t_postal and s1_postal==t_postal else 0.0\n"
    "    country_ag = 1.0 if s1_country==t_country else 0.0\n"
    "    s1nm = 1.0 if not s1_norm else 0.0\n"
    "    tnm  = 1.0 if not t_norm  else 0.0\n"
    "    s1am = 1.0 if not s1_addr else 0.0\n"
    "    tam  = 1.0 if not t_addr  else 0.0\n"
    "    rank_f = 1.0/rank if rank>0 else 0.0\n"
    "    pc_f   = float(pass_count)\n"
    "    nxa    = name_sort*addr_sort\n"
    "    nda    = abs(name_sort-addr_sort)\n"
    "    return [exact_raw,exact_norm,name_sort,name_set,jw,lev,name_char,name_sub,\n"
    "            addr_exact,addr_sort,addr_set,addr_jac,addr_char,num_ov,postal_m,\n"
    "            country_ag,s1nm,tnm,s1am,tam,rank_f,pc_f,nxa,nda]\n"
    "\n"
    "def build_features(df):\n"
    "    n = len(df)\n"
    "    X = np.empty((n,len(FEATURE_NAMES)),dtype=np.float32)\n"
    "    y = df['label'].to_numpy(dtype=np.int32)\n"
    "    for i in range(n):\n"
    "        r = df.iloc[i]\n"
    "        X[i] = compute_pair_features(\n"
    "            str(r.get('s1_raw_name','') or ''), str(r.get('s1_norm_name','') or ''),\n"
    "            str(r.get('s1_norm_addr','') or ''), str(r.get('s1_postal','') or ''),\n"
    "            str(r.get('s1_door','') or ''),\n"
    "            str(r.get('t_raw_name','') or ''),  str(r.get('t_norm_name','') or ''),\n"
    "            str(r.get('t_norm_addr','') or ''),  str(r.get('t_postal','') or ''),\n"
    "            str(r.get('t_door','') or ''),\n"
    "            str(r.get('s1_country','') or ''),   str(r.get('t_country','') or ''),\n"
    "            int(r.get('candidate_rank',1) or 1), int(r.get('pass_count',1) or 1)\n"
    "        )\n"
    "    return X, y\n"
    "\n"
    "print('Extracting features...')\n"
    "t_feat = time.time()\n"
    "df_train_pairs = con.execute('SELECT * FROM train_pairs_selected').df()\n"
    "df_val_pairs   = con.execute(\"SELECT * FROM labeled_topk WHERE split='val'\").df()\n"
    "X_train, y_train = build_features(df_train_pairs)\n"
    "X_val,   y_val   = build_features(df_val_pairs)\n"
    "print(f'Features computed in {time.time()-t_feat:.2f}s')\n"
    "print(f'  X_train: {X_train.shape}  X_val: {X_val.shape}')\n"
    "\n"
    "# ── FEATURE VALIDATION ────────────────────────────────────────────────────\n"
    "print('\\n' + '='*60)\n"
    "print('FEATURE VALIDATION')\n"
    "print('='*60)\n"
    "\n"
    "# 1. NaN / inf check\n"
    "nan_count = int(np.isnan(X_train).sum())\n"
    "inf_count = int(np.isinf(X_train).sum())\n"
    "print(f'NaN values in X_train: {nan_count}')\n"
    "print(f'Inf values in X_train: {inf_count}')\n"
    "if nan_count > 0 or inf_count > 0:\n"
    "    raise ValueError('FEATURE VALIDATION FAILED: NaN or Inf detected in X_train!')\n"
    "print('  [PASS] No NaN or Inf values.')\n"
    "\n"
    "# 2. Feature min / max / mean\n"
    "print('\\nFeature statistics (X_train):')\n"
    "print(f'  {\"Feature\":<30} {\"Min\":>8} {\"Max\":>8} {\"Mean\":>8}')\n"
    "print(f'  {\"-\"*30} {\"-\"*8} {\"-\"*8} {\"-\"*8}')\n"
    "for i, fname in enumerate(FEATURE_NAMES):\n"
    "    print(f'  {fname:<30} {X_train[:,i].min():>8.4f} {X_train[:,i].max():>8.4f} {X_train[:,i].mean():>8.4f}')\n"
    "\n"
    "# 3. Constant features\n"
    "constant_feats = [FEATURE_NAMES[i] for i in range(X_train.shape[1]) if X_train[:,i].std() == 0]\n"
    "print(f'\\nConstant features (zero variance): {constant_feats if constant_feats else \"None\"}')\n"
    "if constant_feats:\n"
    "    print(f'  [WARN] {len(constant_feats)} constant feature(s) detected — consider removing.')\n"
    "else:\n"
    "    print('  [PASS] No constant features.')\n"
    "\n"
    "# 4. Highly correlated / redundant features (|corr| > 0.98)\n"
    "corr_matrix = np.corrcoef(X_train.T)\n"
    "redundant_pairs = []\n"
    "for i in range(len(FEATURE_NAMES)):\n"
    "    for j in range(i+1, len(FEATURE_NAMES)):\n"
    "        if abs(corr_matrix[i,j]) > 0.98:\n"
    "            redundant_pairs.append((FEATURE_NAMES[i], FEATURE_NAMES[j], round(float(corr_matrix[i,j]),4)))\n"
    "if redundant_pairs:\n"
    "    print(f'\\nHighly correlated feature pairs (|r|>0.98):')\n"
    "    for a,b,r in redundant_pairs:\n"
    "        print(f'  {a} <-> {b}  r={r}')\n"
    "    print(f'  [WARN] {len(redundant_pairs)} redundant pair(s) — informational only, not removed.')\n"
    "else:\n"
    "    print('\\n  [PASS] No highly correlated feature pairs (|r|>0.98).')\n"
    "\n"
    "# 5. Feature name alignment\n"
    "df_feat_check = pd.DataFrame(X_train, columns=FEATURE_NAMES)\n"
    "mismatched = [c for c in df_feat_check.columns if c not in FEATURE_NAMES]\n"
    "print(f'\\nFeature name alignment: {len(FEATURE_NAMES)} names, {X_train.shape[1]} columns')\n"
    "if mismatched or len(FEATURE_NAMES) != X_train.shape[1]:\n"
    "    raise ValueError(f'FEATURE VALIDATION FAILED: name/column mismatch! {mismatched}')\n"
    "print('  [PASS] All feature names match X_train columns.')\n"
    "print('\\nFeature validation complete. Proceeding to model training.')\n"
))

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print('Section 10 appended.')
