"""Append strategy F + blocking comparison table + best strategy selection."""
import json

NB = r'c:\Users\akash\OneDrive\Desktop\Amazon ML Challenge\notebooks\train_matching_model_colab.ipynb'

with open(NB, 'r', encoding='utf-8') as f:
    nb = json.load(f)

def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

src_f = (
"# ── Strategy F: 8-pass + perm + ngram + extra address passes, K=50 ───────\n"
"# Extra address passes: a1+a2, postal+a1, door+postal+country\n"
"print('Strategy F: full combined blocking, K=50...')\n"
"t0 = time.time(); m0 = _mem_mb()\n"
"K_F = 50\n"
"con.execute(\"\"\"\n"
"CREATE OR REPLACE TABLE raw_cands_F AS\n"
"SELECT s1_id, target_id, max(pass_count) as pass_count\n"
"FROM (\n"
"    SELECT s1_id, target_id, pass_count FROM raw_cands_E\n"
"    -- extra address pass 1: a1+a2 (first two address tokens)\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id,1 FROM s1_split s JOIN target_pool t\n"
"        ON s.country=t.country AND s.a1=t.a1 AND s.a2=t.a2\n"
"        WHERE length(s.a1)>=4 AND length(s.a2)>=4\n"
"    -- extra address pass 2: postal+a1\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id,1 FROM s1_split s JOIN target_pool t\n"
"        ON s.country=t.country AND s.postal=t.postal AND s.a1=t.a1\n"
"        WHERE s.postal!='' AND length(s.a1)>=4\n"
"    -- extra address pass 3: door+postal (without requiring name token)\n"
"    UNION ALL\n"
"    SELECT s.entity_id,t.entity_id,1 FROM s1_split s JOIN target_pool t\n"
"        ON s.country=t.country AND s.door=t.door AND s.postal=t.postal\n"
"        WHERE length(s.door)>=1 AND s.postal!=''\n"
") sub\n"
"GROUP BY s1_id, target_id;\n"
"\"\"\")\n"
"raw_f = con.execute('SELECT count(*) FROM raw_cands_F').fetchone()[0]\n"
"print(f'  Raw pairs F: {raw_f:,}')\n"
"\n"
"con.execute('CREATE OR REPLACE TABLE topk_F (s1_id VARCHAR, target_id VARCHAR, pass_count BIGINT,'\n"
"            ' split VARCHAR, s1_country VARCHAR,'\n"
"            ' s1_raw_name VARCHAR, s1_raw_addr VARCHAR,'\n"
"            ' s1_norm_name VARCHAR, s1_norm_addr VARCHAR,'\n"
"            ' s1_postal VARCHAR, s1_door VARCHAR,'\n"
"            ' t_country VARCHAR, t_raw_name VARCHAR, t_raw_addr VARCHAR,'\n"
"            ' t_norm_name VARCHAR, t_norm_addr VARCHAR,'\n"
"            ' t_postal VARCHAR, t_door VARCHAR,'\n"
"            ' jaccard_score DOUBLE, candidate_rank BIGINT);')\n"
"s1_ids_f = [r[0] for r in con.execute('SELECT DISTINCT s1_id FROM raw_cands_F ORDER BY s1_id').fetchall()]\n"
"n_chunks_f = (len(s1_ids_f) + RANK_CHUNK_SIZE - 1) // RANK_CHUNK_SIZE\n"
"for ci in range(n_chunks_f):\n"
"    chunk = s1_ids_f[ci*RANK_CHUNK_SIZE:(ci+1)*RANK_CHUNK_SIZE]\n"
"    con.register('_cids', pd.DataFrame({'s1_id': chunk}))\n"
"    con.execute(f\"\"\"\n"
"    INSERT INTO topk_F\n"
"    SELECT s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,\n"
"           s1_norm_name,s1_norm_addr,s1_postal,s1_door,t_country,t_raw_name,t_raw_addr,\n"
"           t_norm_name,t_norm_addr,t_postal,t_door,jaccard_score,candidate_rank\n"
"    FROM (\n"
"        SELECT c.s1_id,c.target_id,c.pass_count,s.split,s.country AS s1_country,\n"
"               s.raw_name AS s1_raw_name,s.raw_addr AS s1_raw_addr,\n"
"               s.norm_name AS s1_norm_name,s.norm_addr AS s1_norm_addr,\n"
"               s.postal AS s1_postal,s.door AS s1_door,\n"
"               t.country AS t_country,t.raw_name AS t_raw_name,t.raw_addr AS t_raw_addr,\n"
"               t.norm_name AS t_norm_name,t.norm_addr AS t_norm_addr,\n"
"               t.postal AS t_postal,t.door AS t_door,\n"
"               (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float/\n"
"                     nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0))+\n"
"                0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float/\n"
"                     nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0)))\n"
"               AS jaccard_score,\n"
"               row_number() OVER (PARTITION BY c.s1_id ORDER BY\n"
"                   (0.6*(len(list_intersect(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))::float/\n"
"                         nullif(len(list_distinct(list_concat(string_split(s.norm_name,' '),string_split(t.norm_name,' ')))),0))+\n"
"                    0.4*(len(list_intersect(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))::float/\n"
"                         nullif(len(list_distinct(list_concat(string_split(s.norm_addr,' '),string_split(t.norm_addr,' ')))),0))) DESC,\n"
"                   c.pass_count DESC) AS candidate_rank\n"
"        FROM raw_cands_F c\n"
"        JOIN _cids x ON c.s1_id=x.s1_id\n"
"        JOIN s1_split s ON c.s1_id=s.entity_id\n"
"        JOIN target_pool t ON c.target_id=t.entity_id\n"
"    ) ranked WHERE candidate_rank <= {K_F};\n"
"    \"\"\")\n"
"tot,s1s,avg,p95 = _cand_stats(con,'topk_F')\n"
"r25 = _recall_at_k(con,'topk_F',25,val_gt)\n"
"r50 = _recall_at_k(con,'topk_F',50,val_gt)\n"
"blocking_results.append({\n"
"    'strategy':'F_full_combined_K50','K':50,\n"
"    'candidate_pairs':tot,'avg_cands':round(avg,1),'p95_cands':p95,\n"
"    'recall_at_25':round(r25,4),'recall_at_50':round(r50,4),'recall_at_100':round(r50,4),\n"
"    'runtime_s':round(time.time()-t0,1),'peak_mem_mb':round(_mem_mb()-m0,1)\n"
"})\n"
"print(f'  pairs={tot:,}  avg={avg:.1f}  p95={p95}  recall@25={r25:.4f}  recall@50={r50:.4f}')\n"
"gc.collect()\n"
"\n"
"# ── BLOCKING COMPARISON TABLE ─────────────────────────────────────────────\n"
"print('\\n' + '='*80)\n"
"print('BLOCKING STRATEGY COMPARISON')\n"
"print('='*80)\n"
"df_blocking = pd.DataFrame(blocking_results)\n"
"display(df_blocking[['strategy','K','candidate_pairs','avg_cands','p95_cands',\n"
"                      'recall_at_25','recall_at_50','recall_at_100','runtime_s','peak_mem_mb']])\n"
"\n"
"# Save blocking comparison\n"
"os.makedirs('/content/experiment_v2', exist_ok=True)\n"
"df_blocking.to_csv('/content/experiment_v2/blocking_comparison.csv', index=False)\n"
"print('Saved: /content/experiment_v2/blocking_comparison.csv')\n"
"\n"
"# Select best strategy by recall@50 (primary) then candidate_pairs (secondary — prefer fewer)\n"
"best_blocking = df_blocking.sort_values(\n"
"    ['recall_at_50','candidate_pairs'], ascending=[False, True]\n"
").iloc[0]\n"
"BEST_STRATEGY = best_blocking['strategy']\n"
"BEST_TOPK_TABLE = {\n"
"    'A_8pass_K25':       'topk_candidates',\n"
"    'B_8pass_K50':       'topk_B',\n"
"    'C_8pass_K100':      'topk_C',\n"
"    'D_8pass_perm_K50':  'topk_D',\n"
"    'E_8pass_perm_ngram_K50': 'topk_E',\n"
"    'F_full_combined_K50':    'topk_F',\n"
"}.get(BEST_STRATEGY, 'topk_F')\n"
"print(f'\\nBest blocking strategy: {BEST_STRATEGY}  (table: {BEST_TOPK_TABLE})')\n"
"print(f'  recall@50={best_blocking[\"recall_at_50\"]:.4f}  avg_cands={best_blocking[\"avg_cands\"]}')\n"
)

nb['cells'].append(code(src_f))

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
print(f'Cells: {len(nb["cells"])}  Part4c written.')
