import json, os

nb_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_matching_model_colab.ipynb'))
with open(nb_path, 'r', encoding='utf-8') as f:
    NB = json.load(f)

assert NB['cells'][20]['cell_type'] == 'code'
assert 'FEATURE_NAMES' in NB['cells'][20]['source']

NEW_SRC = (
    "import gc\n"
    "\n"
    "FEATURE_NAMES = [\n"
    "    'name_exact_raw','name_exact_norm','name_token_sort_ratio','name_token_set_ratio',\n"
    "    'name_jaro_winkler','name_levenshtein_ratio','name_char_sim','name_substring_containment',\n"
    "    'addr_exact_norm','addr_token_sort_ratio','addr_token_set_ratio','addr_token_jaccard',\n"
    "    'addr_char_sim','addr_num_overlap','addr_postal_match',\n"
    "    'country_agreement','s1_name_missing','t_name_missing','s1_addr_missing','t_addr_missing',\n"
    "    'candidate_rank','blocking_pass_count','name_x_addr','name_diff_addr'\n"
    "]\n"
    "N_FEAT = len(FEATURE_NAMES)\n"
    "FEATURE_CHUNK_SIZE = 50000\n"
    "\n"
    "from rapidfuzz import fuzz, distance\n"
    "\n"
    "def compute_pair_features(s1_raw,s1_norm,s1_addr,s1_postal,s1_door,\n"
    "                           t_raw,t_norm,t_addr,t_postal,t_door,\n"
    "                           s1_country,t_country,rank,pass_count):\n"
    "    exact_raw  = 1.0 if s1_raw and s1_raw==t_raw else 0.0\n"
    "    exact_norm = 1.0 if s1_norm and s1_norm==t_norm else 0.0\n"
    "    name_sort  = fuzz.token_sort_ratio(s1_norm,t_norm)/100.0\n"
    "    name_set   = fuzz.token_set_ratio(s1_norm,t_norm)/100.0\n"
    "    jw         = distance.JaroWinkler.similarity(s1_norm,t_norm)\n"
    "    lev        = distance.Levenshtein.normalized_similarity(s1_norm,t_norm)\n"
    "    name_char  = fuzz.ratio(s1_norm,t_norm)/100.0\n"
    "    name_sub   = 1.0 if (s1_norm and t_norm and (s1_norm in t_norm or t_norm in s1_norm)) else 0.0\n"
    "    addr_exact = 1.0 if s1_addr and s1_addr==t_addr else 0.0\n"
    "    addr_sort  = fuzz.token_sort_ratio(s1_addr,t_addr)/100.0\n"
    "    addr_set   = fuzz.token_set_ratio(s1_addr,t_addr)/100.0\n"
    "    s1_at = set(s1_addr.split()) if s1_addr else set()\n"
    "    t_at  = set(t_addr.split())  if t_addr  else set()\n"
    "    addr_jac   = len(s1_at&t_at)/len(s1_at|t_at) if (s1_at or t_at) else 0.0\n"
    "    addr_char  = fuzz.ratio(s1_addr,t_addr)/100.0\n"
    "    s1_nums = {w for w in s1_at if w.isdigit()}\n"
    "    t_nums  = {w for w in t_at  if w.isdigit()}\n"
    "    if s1_nums and t_nums:           num_ov = len(s1_nums&t_nums)/len(s1_nums|t_nums)\n"
    "    elif not s1_nums and not t_nums: num_ov = 0.5\n"
    "    else:                            num_ov = 0.0\n"
    "    postal_m   = 1.0 if s1_postal and t_postal and s1_postal==t_postal else 0.0\n"
    "    country_ag = 1.0 if s1_country==t_country else 0.0\n"
    "    s1nm = 1.0 if not s1_norm else 0.0\n"
    "    tnm  = 1.0 if not t_norm  else 0.0\n"
    "    s1am = 1.0 if not s1_addr else 0.0\n"
    "    tam  = 1.0 if not t_addr  else 0.0\n"
    "    rank_f = 1.0/rank if rank>0 else 0.0\n"
    "    pc_f   = float(pass_count)\n"
    "    nxa    = name_sort*addr_sort\n"
    "    nda    = abs(name_sort-addr_sort)\n"
    "    return [exact_raw,exact_norm,name_sort,name_set,jw,lev,name_char,name_sub,\n"
    "            addr_exact,addr_sort,addr_set,addr_jac,addr_char,num_ov,postal_m,\n"
    "            country_ag,s1nm,tnm,s1am,tam,rank_f,pc_f,nxa,nda]\n"
    "\n"
    "def _fill_X_from_chunk(df_chunk, X, y, row_offset):\n"
    "    \"\"\"Fill pre-allocated X/y arrays from a pandas chunk. No copy returned.\"\"\"\n"
    "    n = len(df_chunk)\n"
    "    s1_raw  = df_chunk['s1_raw_name'].fillna('').values\n"
    "    s1_norm = df_chunk['s1_norm_name'].fillna('').values\n"
    "    s1_addr = df_chunk['s1_norm_addr'].fillna('').values\n"
    "    s1_post = df_chunk['s1_postal'].fillna('').values\n"
    "    s1_door = df_chunk['s1_door'].fillna('').values\n"
    "    s1_coun = df_chunk['s1_country'].fillna('').values\n"
    "    t_raw   = df_chunk['t_raw_name'].fillna('').values\n"
    "    t_norm  = df_chunk['t_norm_name'].fillna('').values\n"
    "    t_addr  = df_chunk['t_norm_addr'].fillna('').values\n"
    "    t_post  = df_chunk['t_postal'].fillna('').values\n"
    "    t_door  = df_chunk['t_door'].fillna('').values\n"
    "    t_coun  = df_chunk['t_country'].fillna('').values\n"
    "    ranks   = df_chunk['candidate_rank'].values\n"
    "    passes  = df_chunk['pass_count'].values\n"
    "    labels  = df_chunk['label'].values\n"
    "    for i in range(n):\n"
    "        X[row_offset+i] = compute_pair_features(\n"
    "            str(s1_raw[i] or ''), str(s1_norm[i] or ''), str(s1_addr[i] or ''),\n"
    "            str(s1_post[i] or ''), str(s1_door[i] or ''),\n"
    "            str(t_raw[i] or ''),  str(t_norm[i] or ''),  str(t_addr[i] or ''),\n"
    "            str(t_post[i] or ''), str(t_door[i] or ''),\n"
    "            str(s1_coun[i] or ''), str(t_coun[i] or ''),\n"
    "            int(ranks[i] or 1), int(passes[i] or 1)\n"
    "        )\n"
    "        y[row_offset+i] = int(labels[i])\n"
    "\n"
    "# ── MEMORY REPORT ─────────────────────────────────────────────────────────\n"
    "def _mem_report(label, n_rows, n_cols=N_FEAT, dtype_bytes=4):\n"
    "    mb = n_rows * n_cols * dtype_bytes / 1024 / 1024\n"
    "    try:\n"
    "        import psutil\n"
    "        proc_mb = psutil.Process().memory_info().rss / 1024 / 1024\n"
    "        print(f'  {label:<35} rows={n_rows:>9,}  cols={n_cols}  est={mb:>7.1f}MB  proc={proc_mb:>7.1f}MB')\n"
    "    except ImportError:\n"
    "        print(f'  {label:<35} rows={n_rows:>9,}  cols={n_cols}  est={mb:>7.1f}MB')\n"
    "\n"
    "print('=' * 70)\n"
    "print('MEMORY REPORT — before feature allocation')\n"
    "print('=' * 70)\n"
    "raw_pairs_cnt  = con.execute('SELECT count(*) FROM raw_candidate_pairs').fetchone()[0]\n"
    "topk_cnt       = con.execute('SELECT count(*) FROM topk_candidates').fetchone()[0]\n"
    "train_cnt      = con.execute('SELECT count(*) FROM train_pairs_selected').fetchone()[0]\n"
    "val_cnt        = con.execute(\"SELECT count(*) FROM labeled_topk WHERE split='val'\").fetchone()[0]\n"
    "_mem_report('Raw candidate pairs (IDs only)',  raw_pairs_cnt, n_cols=3)\n"
    "_mem_report('Top-K candidate pairs (full row)', topk_cnt,     n_cols=20)\n"
    "_mem_report('Training pairs (full row)',         train_cnt,    n_cols=20)\n"
    "_mem_report('Validation pairs (full row)',        val_cnt,     n_cols=20)\n"
    "_mem_report('X_train (float32)',                 train_cnt,    n_cols=N_FEAT, dtype_bytes=4)\n"
    "_mem_report('X_val   (float32)',                 val_cnt,      n_cols=N_FEAT, dtype_bytes=4)\n"
    "print()\n"
    "\n"
    "# ── CHUNKED TRAINING FEATURE EXTRACTION ───────────────────────────────────\n"
    "print(f'Chunked training feature extraction (chunk={FEATURE_CHUNK_SIZE:,})...')\n"
    "t_feat = time.time()\n"
    "\n"
    "X_train = np.empty((train_cnt, N_FEAT), dtype=np.float32)\n"
    "y_train = np.empty(train_cnt, dtype=np.int32)\n"
    "\n"
    "TRAIN_COLS = ('s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,'\n"
    "              's1_norm_name,s1_norm_addr,s1_postal,s1_door,'\n"
    "              't_country,t_raw_name,t_raw_addr,t_norm_name,t_norm_addr,t_postal,t_door,'\n"
    "              'jaccard_score,candidate_rank,label')\n"
    "\n"
    "offset = 0\n"
    "n_train_chunks = (train_cnt + FEATURE_CHUNK_SIZE - 1) // FEATURE_CHUNK_SIZE\n"
    "for ci in range(n_train_chunks):\n"
    "    chunk_df = con.execute(\n"
    "        f'SELECT {TRAIN_COLS} FROM train_pairs_selected'\n"
    "        f' LIMIT {FEATURE_CHUNK_SIZE} OFFSET {ci * FEATURE_CHUNK_SIZE}'\n"
    "    ).df()\n"
    "    _fill_X_from_chunk(chunk_df, X_train, y_train, offset)\n"
    "    offset += len(chunk_df)\n"
    "    del chunk_df\n"
    "    gc.collect()\n"
    "    if (ci + 1) % 5 == 0 or ci == n_train_chunks - 1:\n"
    "        print(f'  train chunk {ci+1}/{n_train_chunks}  rows filled: {offset:,}')\n"
    "\n"
    "# ── CHUNKED VALIDATION FEATURE EXTRACTION ─────────────────────────────────\n"
    "# Retain only minimal columns needed for threshold search + labels\n"
    "# Text columns for error analysis are re-fetched from DuckDB later (on demand)\n"
    "print(f'Chunked validation feature extraction (chunk={FEATURE_CHUNK_SIZE:,})...')\n"
    "\n"
    "X_val   = np.empty((val_cnt, N_FEAT), dtype=np.float32)\n"
    "y_val   = np.empty(val_cnt, dtype=np.int32)\n"
    "# val_meta: minimal columns for threshold search — s1_id, target_id, label\n"
    "val_s1_ids  = np.empty(val_cnt, dtype=object)\n"
    "val_tgt_ids = np.empty(val_cnt, dtype=object)\n"
    "\n"
    "VAL_COLS = ('s1_id,target_id,pass_count,split,s1_country,s1_raw_name,s1_raw_addr,'\n"
    "            's1_norm_name,s1_norm_addr,s1_postal,s1_door,'\n"
    "            't_country,t_raw_name,t_raw_addr,t_norm_name,t_norm_addr,t_postal,t_door,'\n"
    "            'jaccard_score,candidate_rank,label')\n"
    "\n"
    "offset = 0\n"
    "n_val_chunks = (val_cnt + FEATURE_CHUNK_SIZE - 1) // FEATURE_CHUNK_SIZE\n"
    "for ci in range(n_val_chunks):\n"
    "    chunk_df = con.execute(\n"
    "        f\"SELECT {VAL_COLS} FROM labeled_topk WHERE split='val'\"\n"
    "        f' LIMIT {FEATURE_CHUNK_SIZE} OFFSET {ci * FEATURE_CHUNK_SIZE}'\n"
    "    ).df()\n"
    "    _fill_X_from_chunk(chunk_df, X_val, y_val, offset)\n"
    "    val_s1_ids [offset:offset+len(chunk_df)] = chunk_df['s1_id'].values\n"
    "    val_tgt_ids[offset:offset+len(chunk_df)] = chunk_df['target_id'].values\n"
    "    offset += len(chunk_df)\n"
    "    del chunk_df\n"
    "    gc.collect()\n"
    "    if (ci + 1) % 5 == 0 or ci == n_val_chunks - 1:\n"
    "        print(f'  val chunk {ci+1}/{n_val_chunks}  rows filled: {offset:,}')\n"
    "\n"
    "print(f'Feature extraction complete in {time.time()-t_feat:.1f}s')\n"
    "print(f'  X_train: {X_train.shape}  X_val: {X_val.shape}')\n"
    "print(f'  X_train RAM: {X_train.nbytes/1024/1024:.1f}MB  X_val RAM: {X_val.nbytes/1024/1024:.1f}MB')\n"
    "\n"
    "# ── FEATURE VALIDATION ────────────────────────────────────────────────────\n"
    "print('\\n' + '='*60)\n"
    "print('FEATURE VALIDATION')\n"
    "print('='*60)\n"
    "\n"
    "nan_count = int(np.isnan(X_train).sum())\n"
    "inf_count = int(np.isinf(X_train).sum())\n"
    "print(f'NaN values in X_train: {nan_count}')\n"
    "print(f'Inf values in X_train: {inf_count}')\n"
    "if nan_count > 0 or inf_count > 0:\n"
    "    raise ValueError('FEATURE VALIDATION FAILED: NaN or Inf detected in X_train!')\n"
    "print('  [PASS] No NaN or Inf values.')\n"
    "\n"
    "print('\\nFeature statistics (X_train):')\n"
    "print(f'  {\"Feature\":<30} {\"Min\":>8} {\"Max\":>8} {\"Mean\":>8}')\n"
    "print(f'  {\"-\"*30} {\"-\"*8} {\"-\"*8} {\"-\"*8}')\n"
    "for i, fname in enumerate(FEATURE_NAMES):\n"
    "    print(f'  {fname:<30} {X_train[:,i].min():>8.4f} {X_train[:,i].max():>8.4f} {X_train[:,i].mean():>8.4f}')\n"
    "\n"
    "constant_feats = [FEATURE_NAMES[i] for i in range(N_FEAT) if X_train[:,i].std() == 0]\n"
    "print(f'\\nConstant features: {constant_feats if constant_feats else \"None\"}')\n"
    "if constant_feats:\n"
    "    print(f'  [WARN] {len(constant_feats)} constant feature(s).')\n"
    "else:\n"
    "    print('  [PASS] No constant features.')\n"
    "\n"
    "corr_matrix = np.corrcoef(X_train.T)\n"
    "redundant_pairs = []\n"
    "for i in range(N_FEAT):\n"
    "    for j in range(i+1, N_FEAT):\n"
    "        if abs(corr_matrix[i,j]) > 0.98:\n"
    "            redundant_pairs.append((FEATURE_NAMES[i], FEATURE_NAMES[j], round(float(corr_matrix[i,j]),4)))\n"
    "if redundant_pairs:\n"
    "    print(f'\\nHighly correlated pairs (|r|>0.98):')\n"
    "    for a,b,r in redundant_pairs:\n"
    "        print(f'  {a} <-> {b}  r={r}')\n"
    "    print(f'  [WARN] {len(redundant_pairs)} pair(s) — informational only.')\n"
    "else:\n"
    "    print('\\n  [PASS] No highly correlated feature pairs (|r|>0.98).')\n"
    "\n"
    "if N_FEAT != X_train.shape[1]:\n"
    "    raise ValueError(f'FEATURE VALIDATION FAILED: {N_FEAT} names but {X_train.shape[1]} columns!')\n"
    "print(f'\\n  [PASS] Feature name alignment: {N_FEAT} names == {X_train.shape[1]} columns.')\n"
    "print('\\nFeature validation complete. Proceeding to model training.')\n"
)

NB['cells'][20]['source'] = NEW_SRC

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(NB, f, indent=2, ensure_ascii=False)
print('Fix 3 applied: Section 10 code replaced with chunked extraction.')
