"""Append Section 26: error analysis v2."""
import json

NB = r'c:\Users\akash\OneDrive\Desktop\Amazon ML Challenge\notebooks\train_matching_model_colab.ipynb'

with open(NB, 'r', encoding='utf-8') as f:
    nb = json.load(f)

def md(src): return {"cell_type":"markdown","metadata":{},"source":src}
def code(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

nb['cells'].append(md(
"### Section 26: Error Analysis v2\n\n"
"Analyzes FP/FN for the best v2 model and blocking misses (true matches never in candidate pool).\n"
))

src_26 = (
"import gc\n"
"from collections import defaultdict\n"
"from rapidfuzz import fuzz as _fuzz\n"
"import pandas as _pd_v2\n"
"import numpy as _np2\n"
"\n"
"pred_v2 = (best_v2_probs >= best_v2_tau).astype(_np2.int32)\n"
"fp_mask_v2 = (y_val_v2 == 0) & (pred_v2 == 1)\n"
"fn_mask_v2 = (y_val_v2 == 1) & (pred_v2 == 0)\n"
"print(f'Best v2 model: {best_v2_name}  tau*={best_v2_tau}')\n"
"print(f'False Positives: {fp_mask_v2.sum():,}  False Negatives: {fn_mask_v2.sum():,}')\n"
"\n"
"# ── FALSE POSITIVE ANALYSIS ────────────────────────────────────────────────\n"
"fp_s1_ids_v2  = val_s1_ids_v2[fp_mask_v2].tolist()\n"
"fp_tgt_ids_v2 = val_tgt_ids_v2[fp_mask_v2].tolist()\n"
"\n"
"fp_cats_v2 = defaultdict(int)\n"
"if fp_s1_ids_v2:\n"
"    con.register('_fp_s1_v2',  _pd_v2.DataFrame({'s1_id':  fp_s1_ids_v2}))\n"
"    con.register('_fp_tgt_v2', _pd_v2.DataFrame({'target_id': fp_tgt_ids_v2}))\n"
"    df_fp_v2 = con.execute(\"\"\"\n"
"        SELECT tk.s1_id, tk.target_id,\n"
"               tk.s1_norm_name, tk.t_norm_name,\n"
"               tk.s1_norm_addr, tk.t_norm_addr,\n"
"               tk.s1_door, tk.t_door\n"
"        FROM labeled_best tk\n"
"        WHERE tk.s1_id    IN (SELECT s1_id    FROM _fp_s1_v2)\n"
"          AND tk.target_id IN (SELECT target_id FROM _fp_tgt_v2)\n"
"          AND tk.split = 'val' AND tk.label = 0\n"
"    \"\"\").df()\n"
"    for _, r in df_fp_v2.iterrows():\n"
"        ns  = _fuzz.token_sort_ratio(str(r.get('s1_norm_name','') or ''), str(r.get('t_norm_name','') or ''))\n"
"        as_ = _fuzz.token_sort_ratio(str(r.get('s1_norm_addr','') or ''), str(r.get('t_norm_addr','') or ''))\n"
"        sd  = str(r.get('s1_door','') or '')\n"
"        td  = str(r.get('t_door','') or '')\n"
"        sn  = str(r.get('s1_norm_name','') or '')\n"
"        if ns >= 85 and as_ < 40:                 fp_cats_v2['same_name_diff_address'] += 1\n"
"        elif as_ >= 80 and ns < 40:               fp_cats_v2['same_address_diff_business'] += 1\n"
"        elif sd and td and sd != td and ns >= 70: fp_cats_v2['address_number_conflict'] += 1\n"
"        elif len(sn.replace(' ','')) <= 5:        fp_cats_v2['abbreviation_collision'] += 1\n"
"        else:                                     fp_cats_v2['generic_name_collision'] += 1\n"
"    fp_total_v2 = max(len(df_fp_v2), 1)\n"
"    del df_fp_v2; gc.collect()\n"
"else:\n"
"    fp_total_v2 = 1\n"
"\n"
"fp_df_v2 = _pd_v2.DataFrame([{'Category':k,'Count':v,'Pct':f'{v/fp_total_v2*100:.1f}%'}\n"
"                              for k,v in sorted(fp_cats_v2.items(), key=lambda x:-x[1])])\n"
"print('\\nFalse Positive Categories (v2):')\n"
"display(fp_df_v2)\n"
"\n"
"# ── FALSE NEGATIVE ANALYSIS ────────────────────────────────────────────────\n"
"fn_s1_ids_v2  = val_s1_ids_v2[fn_mask_v2].tolist()\n"
"fn_tgt_ids_v2 = val_tgt_ids_v2[fn_mask_v2].tolist()\n"
"\n"
"fn_cats_v2 = defaultdict(int)\n"
"if fn_s1_ids_v2:\n"
"    con.register('_fn_s1_v2',  _pd_v2.DataFrame({'s1_id':  fn_s1_ids_v2}))\n"
"    con.register('_fn_tgt_v2', _pd_v2.DataFrame({'target_id': fn_tgt_ids_v2}))\n"
"    df_fn_v2 = con.execute(\"\"\"\n"
"        SELECT tk.s1_id, tk.target_id,\n"
"               tk.s1_norm_name, tk.t_norm_name,\n"
"               tk.s1_norm_addr, tk.t_norm_addr,\n"
"               tk.s1_door, tk.t_door\n"
"        FROM labeled_best tk\n"
"        WHERE tk.s1_id    IN (SELECT s1_id    FROM _fn_s1_v2)\n"
"          AND tk.target_id IN (SELECT target_id FROM _fn_tgt_v2)\n"
"          AND tk.split = 'val' AND tk.label = 1\n"
"    \"\"\").df()\n"
"    for _, r in df_fn_v2.iterrows():\n"
"        ns  = _fuzz.token_sort_ratio(str(r.get('s1_norm_name','') or ''), str(r.get('t_norm_name','') or ''))\n"
"        as_ = _fuzz.token_sort_ratio(str(r.get('s1_norm_addr','') or ''), str(r.get('t_norm_addr','') or ''))\n"
"        sn  = str(r.get('s1_norm_name','') or '')\n"
"        tn  = str(r.get('t_norm_name','') or '')\n"
"        sa  = str(r.get('s1_norm_addr','') or '')\n"
"        ta  = str(r.get('t_norm_addr','') or '')\n"
"        if ns < 50 and as_ < 50:                  fn_cats_v2['both_name_addr_weak'] += 1\n"
"        elif ns < 60:                             fn_cats_v2['name_typo_or_variation'] += 1\n"
"        elif as_ < 60:                            fn_cats_v2['address_typo_or_missing'] += 1\n"
"        elif not sn or not tn:                    fn_cats_v2['missing_business_name'] += 1\n"
"        elif not sa or not ta:                    fn_cats_v2['missing_address'] += 1\n"
"        else:                                     fn_cats_v2['other_low_confidence'] += 1\n"
"    fn_total_v2 = max(len(df_fn_v2), 1)\n"
"    del df_fn_v2; gc.collect()\n"
"else:\n"
"    fn_total_v2 = 1\n"
"\n"
"fn_df_v2 = _pd_v2.DataFrame([{'Category':k,'Count':v,'Pct':f'{v/fn_total_v2*100:.1f}%'}\n"
"                              for k,v in sorted(fn_cats_v2.items(), key=lambda x:-x[1])])\n"
"print('\\nFalse Negative Categories (v2):')\n"
"display(fn_df_v2)\n"
"\n"
"# ── BLOCKING MISSES ────────────────────────────────────────────────────────\n"
"# True matches that never appeared in the best candidate pool\n"
"print('\\nBlocking miss analysis...')\n"
"blocking_miss_cnt = con.execute(f\"\"\"\n"
"    SELECT count(*) FROM (\n"
"        SELECT s.entity_id, unnest(string_split(s.matched_entity_ids,',')) as true_tgt\n"
"        FROM s1_split s\n"
"        WHERE s.split='val'\n"
"          AND s.matched_entity_ids IS NOT NULL\n"
"          AND trim(s.matched_entity_ids) != ''\n"
"    ) gt\n"
"    WHERE NOT EXISTS (\n"
"        SELECT 1 FROM {BEST_TOPK_TABLE} c\n"
"        WHERE c.s1_id = gt.entity_id AND c.target_id = gt.true_tgt\n"
"    )\n"
"\"\"\").fetchone()[0]\n"
"total_true_links = con.execute(\"\"\"\n"
"    SELECT sum(match_count) FROM s1_split WHERE split='val' AND match_count > 0\n"
"\"\"\").fetchone()[0] or 1\n"
"blocking_miss_pct = blocking_miss_cnt / total_true_links * 100\n"
"print(f'  True links in val:          {total_true_links:,}')\n"
"print(f'  Blocking misses:            {blocking_miss_cnt:,}  ({blocking_miss_pct:.2f}%)')\n"
"print(f'  Blocking recall (val):      {100-blocking_miss_pct:.2f}%')\n"
"\n"
"# Save error analysis\n"
"err_rows = []\n"
"for cat, cnt in fp_cats_v2.items():\n"
"    err_rows.append({'type':'FP','category':cat,'count':cnt,'pct':round(cnt/fp_total_v2*100,1)})\n"
"for cat, cnt in fn_cats_v2.items():\n"
"    err_rows.append({'type':'FN','category':cat,'count':cnt,'pct':round(cnt/fn_total_v2*100,1)})\n"
"err_rows.append({'type':'BLOCKING_MISS','category':'never_in_pool',\n"
"                 'count':blocking_miss_cnt,'pct':round(blocking_miss_pct,2)})\n"
"_pd_v2.DataFrame(err_rows).to_csv('/content/experiment_v2/error_analysis_v2.csv', index=False)\n"
"print('Saved: /content/experiment_v2/error_analysis_v2.csv')\n"
)

nb['cells'].append(code(src_26))

with open(NB, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
print(f'Cells: {len(nb["cells"])}  Part9 written.')
